### ISSUE TITLE
[Bug]: Quad and double drawers delete inventory when broken.

### ISSUE THREAD

**Issue by Sammcb** [MattiDragon/ExtendedDrawers#10]
### Description of the issue

When a single drawer is broken in survival, it can be picked up and placed down again and keeps its inventory and upgrades. Quad and double drawers loose their inventory and upgrades when broken and placed again.

### Reproduction steps

1. Place down a double/quad drawer
2. Put items in drawer (i.e. 64 stone)
3. Break drawer (such as with a diamond axe)
4. Pick up drawer item
5. Place drawer down again
6. Drawer will have no items or upgrades

### Mod version

v1.3.1

### Operating System

macOS 12.4

### Minecraft version

1.18.2

### Other mods

Fabric API: 0.57.0

### Server

Not tested

### Client

Happens

### Logs

N/A

**Comment by Geethebluesky** [comment]
I confirm I have the same behavior with double and quad drawers (lost 20 stacks of terracotta of various colors just now), both double and quads also lost their upgrades, The single drawer kept its upgrade and its contents though.

**Comment by MattiDragon** [comment]
I seem to have forgot to apply the content copying to non-single drawers. Will be fixed in the next release

**Comment by MattiDragon** [comment]
This has been fixed in version 1.3.2. Feel free to reopen if the issue persists.
