### ISSUE TITLE
[Feature]: Backport compacting drawers to 1.18.2

### ISSUE THREAD

**Issue by MrStickyPiston** [MattiDragon/ExtendedDrawers#100]
### Description of the feature

Compacting drawers but 1.18.2

### How does it make the mod better?

I play on 1.18.2 fabric with a lot of mods that arent ported yet and probably never will. I would really like the compacting drawer as it would massively help me with building a factory for nearly everything automizable in the modpack.
If you wont do it because you dont have time its no problem, i know newer versions are the future.

Thanks for reading.

**Comment by MattiDragon** [comment]
Won't happen unless someone else does it. I haven't touched the 1.18 codebase in a long time and it's quite different from the current one. 1.18 will only be considered for updates if there's a critical bug that needs fixing.
