### ISSUE TITLE
[Bug]: Storage Upgrade Dupe

### ISSUE THREAD

**Issue by lpjn** [MattiDragon/ExtendedDrawers#106]
### Description of the issue

1. put in any upgrade
2. fill the storage
3. take out the upgrade
4. re-enter the menu.

You then get a dupe of the storage upgrade.

Also happens if u switch the upgrade with a higher tier

https://github.com/MattiDragon/ExtendedDrawers/assets/38690189/f0f56158-202d-4dd5-bebf-cb9b484cbbe1

### Reproduction steps

1. put in any upgrade
2. fill the storage
3. take out the upgrade
4. re-enter the menu.

### Mod version

2.1.1+mc.1.20.1

### Operating System

Ubuntu 22.04

### Minecraft version

1.20.1

### Other mods

[ad_astra-fabric-1.20.1-1.15.18.jar.txt](https://github.com/MattiDragon/ExtendedDrawers/files/15170495/ad_astra-fabric-1.20.1-1.15.18.jar.txt)

### Server

Happens

### Client

Happens

### Logs

No logging when duping on the server

**Comment by MattiDragon** [comment]
The gui is added by ExtendedDrawersAddon. They are responsible for any issues caused by it. If you can reproduce this without the addon, please reopen
