### ISSUE TITLE
[Bug]: Voiding mode with multiple drawers of same type

### ISSUE THREAD

**Issue by nojomyth-dev** [MattiDragon/ExtendedDrawers#109]
### Description of the issue

When having multiple drawers of the same item type in a network, and all drawers have voiding enabled (or the one with the highest priority), no items get added to the other drawers. Instead, all further items get voided instead of being added to the extra drawers, When removing the voiding mode, it works as expected

### Reproduction steps

1. Place down 2 drawers and an access point.
2. Add one item to both drawers (same type), lock the drawers and void them.
3. Fill the drawers via hoppers.
4. After one drawer is full, no further items get inserted into the next drawer.

### Mod version

2.1.1

### Operating System

Unraid / Windows

### Minecraft version

1.20.4

### Other mods

Not relevant

### Server

Happens

### Client

Not tested

### Logs

Not relevant

**Comment by MattiDragon** [comment]
Figured out what's causing this. Drawers are ordered such that voiding drawers are placed last in the list to check. However, when there's multiple of them, one will eat the items before they reach the other. I can't really do anything for this without reworking how drawers are ordered (it can only change when you place more or change the modifiers of a drawer)
