### ISSUE TITLE
[Feature]: Preview drawer items/upgrades when in inventory

### ISSUE THREAD

**Issue by Sammcb** [MattiDragon/ExtendedDrawers#11]
### Description of the feature

When a drawer is in your inventory, it would be nice to have some kind of preview of what items it contains and what upgrades it has. It might also be nice to integrate with [ShuklerBoxTooltip](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip), but certainly not necessary (since even a quad drawer can only have up to 4 different kinds of items).

### How does it make the mod better?

As of v1.3.1 there is no way to differentiate drawers with items/upgrades when they are in the inventory. This usually means the drawers have to be placed in the world to sort them out which is a lot less convenient compared to seeing which drawer is which in the inventory before placing. This change would make picking up and placing lots of drawers with items in them much easier.

**Comment by MattiDragon** [comment]
Good idea. Might implement it at some point if I have time

**Comment by MattiDragon** [comment]
Coming next update!
![](https://cdn.discordapp.com/attachments/523251999899385875/1000762798239928380/unknown.png)

**Comment by MattiDragon** [comment]
This has been added in version 1.3.2.
