### ISSUE TITLE
[Bug]: Drawer access point is inert

### ISSUE THREAD

**Issue by jdmccabe** [MattiDragon/ExtendedDrawers#111]
### Description of the issue

Right clicking on the Drawer Access Point to move inventory items into the drawer network stopped working.  Neither single click or double click with the right mouse button work.  Neither the item stack in my active hand nor any of the items in my inventory get moved into the drawers.  The Drawer Access Point used to work perfectly for many days of playing, but then it stopped.  The timing of when it stopped working may coincide with when I added a 5th or 6th Drawer Access Point to my network.  The network has around 80 drawers of different types and ~40 drawer connectors.  Restarting the game did not have any effect.  Everything works perfectly in a new world, and I creating large drawer networks appears to work fine.

### Reproduction steps

1. Create a drawer network with >80 drawers, >40 drawer connectors, >6 Drawer Access Points
2. Place items of different types in ~40 drawers 3
3. Lock the item type for all drawers 
4. Play for a few weeks.
5. I haven't actually been able to reproduce this.

### Mod version

2.1.1

### Operating System

Windows 11

### Minecraft version

1.20.1

### Other mods

Fabric API 0.92.0
many others.   I was unable to narrow down the mod list since the save files won't load without the mods active.

### Server

Not tested

### Client

Not tested

### Logs

https://gist.github.com/jdmccabe/b3de3b79391d439dcb2b7f2a88d2ed25

**Comment by MattiDragon** [comment]
You can run the `/graphlib extended_drawers:drawers debugrender start` command to see the connections between drawers. If you find a disconnect somewhere in your network, placing those blocks again should fix it.

**Comment by jdmccabe** [comment]
Thank you.  That command is very helpful.
