### ISSUE TITLE
Start crash

### ISSUE THREAD

**Issue by zc1108aaa** [MattiDragon/ExtendedDrawers#112]
### Description of the issue

1

### Reproduction steps

1

### Mod version

2.1.1+mc.1.20.1

### Operating System

windows10

### Minecraft version

1.20.1fabric

### Other mods

1

### Server

Not tested

### Client

Not tested

### Logs

no

### Crash Report

1

### Extra Context

[latest.log](https://github.com/MattiDragon/ExtendedDrawers/files/15464324/latest.log)

**Comment by MattiDragon** [comment]
This seems to be caused by `libertyvillagers`. Why did you report it here?
