### ISSUE TITLE
[Bug]: Draw controller network not working 2

### ISSUE THREAD

**Issue by Jeinerox** [MattiDragon/ExtendedDrawers#115]
### Description of the issue

Hello! I have exactly the same problem as here: https://github.com/mattidragon/extendeddrawers/issues/54
Every time i place a drawer into my network i get `Encountered invalid graph in position when detecting node changes.` warning.
Every time I rebuild the network, it becomes impossible to put some blocks through the access point.

I am the administrator of a small minecraft server and recently I also started having problems with the drawers network. The problem is that the advice provided in recent issue does not work for me :(. I don't see any gaps in the network, and I also don't see duplicate networks using `/graphlib debugrender start` command. I tried to update the blocks on the entire base using `/graphlib updateblocks` command but nothing changes too. 
The only thing that helps is replacing all the connectors with worldedit, but it only helps until I start rebuilding my warehouse again and it doesn't remove the warn `Encountered invalid graph in position when detecting node changes.`.
I have two suggestions as to why the problems might have started: Create cannon or a server crash.
The fact is that we often build buildings in creative mode, and then transfer them to our world with survival using a cannon, and it could happen, then this cannon could somehow put the drawer connector incorrectly.

### Reproduction steps

Sorry, I do not know exactly what causes the bug:(

### Mod version

1.4.5

### Operating System

Ubuntu server 22 LTS, Windows 11

### Minecraft version

1.19.2

### Other mods

**Serverside**
_ExtendedDrawers-1.4.5+mc.1.19.2
fabric-api-0.77.0+1.19.2
fabric-language-kotlin-1.10.19+kotlin.1.9.23
ferritecore-5.0.3-fabric
geckolib-fabric-1.19-3.1.40
graphlib-0.3.7+1.19.2
immersive-portals-2.3.2-mc1.19.2-fabric
inventoryessentials-fabric-1.19-5.0.2
inventorymanagement-1.1.2+1.19
jei-1.19.2-fabric-11.5.2.1006
lazydfu-0.1.3
lithium-fabric-mc1.19.2-0.11.1
mcw-furniture-3.2.0-mc1.19.2fabric
memoryleakfix-fabric-1.17+-1.1.5
MixinConflictHelper-1.2.0
mixintrace-1.1.1+1.17
moonlight-1.19.2-2.3.6-fabric
NoChatReports-FABRIC-1.19.2-v1.13.12
nofade-1.18-2.0.1
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.6
smoothboot-fabric-1.19-1.7.1
starlight-1.1.1+fabric.ae22326
supermartijn642configlib-1.1.8a-fabric-mc1.19
supermartijn642corelib-1.1.17-fabric-mc1.19.2
supplementaries-1.19.2-2.4.21-fabric
TerraBlender-fabric-1.19.2-2.0.1.166
tl_skin_cape_fabric_1.19.1_1.19.4-1.30
worldedit-mod-7.2.12
yosbr-0.1.2
AnvilFix-19.2.1
balm-fabric-1.19.2-4.5.6
chunkloaders-1.2.8a-fabric-mc1.19.2
Chunky-1.3.38
cloth-config-8.3.115-fabric
Clumps-fabric-1.19.2-9.0.0+14
CorgiLib-fabric-1.19.2-1.0.0.34
create-fabric-0.5.1-f-build.1334+mc1.19.2
Debugify-2.8.0
do-a-barrel-roll-2.6.1+1.19.2-fabric
easyauth-mc1.19.1-3.0.0-14_

**Client**
_advancementinfo-1.19.1-fabric0.58.5-1.3.1
animatica-0.5+1.19
antighost-1.19.1-fabric0.58.5-1.1.5
anvil-too-expensive-1.0.0
balm-fabric-1.19.2-4.5.6
bettermounthud-1.2.0
Blanket Client tweaks-1.1.2
borderless-mining-1.1.5+1.19
capes-1.5.2+1.19.2-fabric
cem-0.7.3-1.19
chunkloaders-1.2.8a-fabric-mc1.19.2
CITResewn-1.1.2+1.19.2
cloth-config-8.3.115-fabric
Clumps-fabric-1.19.2-9.0.0+14
colormatic-3.1.2+mc.1.19
continuity-2.0.2+1.19
CorgiLib-fabric-1.19.2-1.0.0.34
create-fabric-0.5.1-f-build.1334+mc1.19.2
CullLessLeaves-1.0.6
do-a-barrel-roll-2.6.1+1.19.2-fabric
enhancedblockentities-0.7.2+1.19.2
entity_texture_features_fabric_1.19.2-5.2.3
entityculling-fabric-1.6.1-mc1.19.2
ExtendedDrawers-1.4.5+mc.1.19.2
fabric-api-0.77.0+1.19.2
fabric-language-kotlin-1.10.19+kotlin.1.9.23
fabricskyboxes-0.7.2+mc1.19.2
fabrishot-1.9.2
farsight-fabric-1.19-2.4
ferritecore-5.0.3-fabric
FpsReducer2-fabric-1.19.2-2.1
fsb-interop-1.3.2+mc1.19.2-build.40
geckolib-fabric-1.19-3.1.40
graphlib-0.3.7+1.19.2
ImmediatelyFast-Fabric-1.2.10+1.19.2
immersive-portals-2.3.2-mc1.19.2-fabric
indium-1.0.9+mc1.19.2
inventoryessentials-fabric-1.19-5.0.2
inventorymanagement-1.1.2+1.19
iris-mc1.19.2-1.4.1
item-model-fix-1.0.3+1.19
jei-1.19.2-fabric-11.6.0.1019
JustEnoughResources-Fabric-1.19.2-1.2.3.243
krypton-0.2.1
lambdabettergrass-1.3.0+1.19
lambdynamiclights-2.2.0+1.19.2
language-reload-1.5.10+1.19.2
lazydfu-0.1.3
lithium-fabric-mc1.19.2-0.11.1
main-menu-credits-1.1.1
malilib-fabric-1.19.2-0.13.0
mcw-furniture-3.2.0-mc1.19.2fabric
memoryleakfix-fabric-1.17+-1.1.5
midnightcontrols-1.7.4+1.19
MixinConflictHelper-1.2.0
mixintrace-1.1.1+1.17
modmenu-4.2.0-beta.2
moonlight-1.19.2-2.3.6-fabric
morechathistory-1.3.0
NoChatReports-FABRIC-1.19.2-v1.13.12
nofade-1.18-2.0.1
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.6
puzzle-1.4.2-1.19
reeses_sodium_options-1.6.4+mc1.19.2-build.93
smoothboot-fabric-1.19-1.7.1
sodium-extra-0.4.16+mc1.19.2-build.90
sodium-fabric-mc1.19.2-0.4.4+build.18
starlight-1.1.1+fabric.ae22326
supermartijn642configlib-1.1.8a-fabric-mc1.19
supermartijn642corelib-1.1.17-fabric-mc1.19.2
supplementaries-1.19.2-2.4.21-fabric
TerraBlender-fabric-1.19.2-2.0.1.166
tl_skin_cape_fabric_1.19.1_1.19.4-1.30
WorldEditCUI-1.19.201
worldedit-mod-7.2.12
Xaeros_Minimap_24.0.2_Fabric_1.19.1
XaerosWorldMap_1.38.1_Fabric_1.19.1
YetAnotherConfigLib-2.2.0-for-1.19.2
yosbr-0.1.2
Zoomify-2.9.0_

### Server

Happens

### Client

Happens

### Logs

Encountered invalid graph in position when detecting node changes.

### Extra Context

Mods, world and my recording with this bug.
https://disk.yandex.ru/d/h6vUUgYbT3n2FQ

**Comment by MattiDragon** [comment]
I've practically dropped support for 1.19 by now and won't be looking into this. The mods codebase was very different back then.

I suspect that the schematicanon somehow broke graphlib, but I don't have time to debug bugs on old versions.
