### ISSUE TITLE
[Feature]: Config size of drawers

### ISSUE THREAD

**Issue by otterpawps** [MattiDragon/ExtendedDrawers#116]
### Description of the feature

Really love this over other drawer-esque inventories, but wish there was a config for how large the drawers can get.

### How does it make the mod better?

Would allow server customization for how powerful the drawers are, allowing a bit cleaner inventory rooms.

**Comment by MattiDragon** [comment]
There is already a config option for this. Under the storage category you can change the drawer capacity value to adjust the base size of drawers.
