### ISSUE TITLE
[Crash]: Continuous crashes on the server side

### ISSUE THREAD

**Issue by TheWanderingTrader** [MattiDragon/ExtendedDrawers#119]
### Description of the issue

The game keeps crashing on the server side and is related to the drawers not rending something

### Reproduction steps

See crash log

### Mod version

v3.0.0

### Operating System

Server(MCPH)

### Minecraft version

1.21

### Other mods

Using a modpack here [https://modrinth.com/modpack/the-trading-post](url)

### Server

Happens

### Client

Not tested

### Logs

https://mclo.gs/eqFOUsB

### Crash Report

https://mclo.gs/3V6FSiP

**Comment by MattiDragon** [comment]
Fixed in v3.0.1
