### ISSUE TITLE
[Feature]: Tags to Drawers

### ISSUE THREAD

**Issue by Laifsyn** [MattiDragon/ExtendedDrawers#12]
### Description of the feature

Give tool tag to the drawers
totally Suggestion: Give the c:chest tag to drawers recipes

### How does it make the mod better?

More convenient to "Mine" them

**Comment by MattiDragon** [comment]
will be added in the next release

**Comment by MattiDragon** [comment]
This has been fixed in version 1.3.2. Feel free to reopen if the issue persists.
