### ISSUE TITLE
[Bug]: Can't handle large max stack size

### ISSUE THREAD

**Issue by Phoupraw** [MattiDragon/ExtendedDrawers#122]
### Description of the issue

When the max stack size of item is set to 99, drawer can't be inserted into any item.
```
Failed to handle packet net.minecraft.class_2885@32997baf, suppressing error
java.lang.ArithmeticException: / by zero
	at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.getCapacity(DrawerSlot.java:141) ~[ExtendedDrawers-3.0.2+mc.1.21.jar:?]
	at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.insert(DrawerSlot.java:81) ~[ExtendedDrawers-3.0.2+mc.1.21.jar:?]
	at io.github.mattidragon.extendeddrawers.storage.DrawerSlot.insert(DrawerSlot.java:22) ~[ExtendedDrawers-3.0.2+mc.1.21.jar:?]
	at io.github.mattidragon.extendeddrawers.block.base.StorageDrawerBlock.method_55766(StorageDrawerBlock.java:154) ~[ExtendedDrawers-3.0.2+mc.1.21.jar:?]
```

### Reproduction steps

1. Turn on config `Stack size affects capcity`
2. Run `/give @p stone[minecraft:max_stack_size=99] 99`
3. Try inserting the items into a drawer
4. Failed and logged error

### Mod version

3.0.2

### Operating System

Windows 10

### Minecraft version

1.21

### Other mods

Loading 240 mods:
	- advanced-xray-fabric 21.0.0
	- advancementscreenshot 4.8
	- animal_feeding_trough 1.1.1+1.21
	- anvilrestoration 2.2
	- appleskin 3.0.2+mc1.21
	- architectury 13.0.3
	- autofish 0.6
	- axesareweapons 1.9.0
	- balm-fabric 21.0.11
	   \-- kuma_api 21.0.4
	- bigbeacons 1.2.7
	- bowinfinityfix 3.1.0
	- breakfree 1.3.0
	- bucketlib 1.21-4.0.0.6
	- cardinal-components 6.1.0
	   |-- cardinal-components-base 6.1.0
	   |-- cardinal-components-block 6.1.0
	   |-- cardinal-components-chunk 6.1.0
	   |-- cardinal-components-entity 6.1.0
	   |-- cardinal-components-item 6.1.0
	   |-- cardinal-components-level 6.1.0
	   |-- cardinal-components-scoreboard 6.1.0
	   \-- cardinal-components-world 6.1.0
	- carpet 1.4.147+v240613
	- cicada 0.8.1+1.21-and-above
	- clientcommands 2.9
	   |-- betterconfig 1.3
	   |-- clientarguments 1.9
	   \-- net_fabricmc_mapping-io 0.5.1
	- cloth-config 15.0.127
	   \-- cloth-basic-math 0.6.1
	- collective 7.70
	- copperhopper 0.9.3+1.21
	- ding 1.5.0
	- discerning_furnace 1.1.0
	- dismountentity 3.3
	- dynamic_fps 3.6.0
	   \-- net_lostluma_battery 1.0.1
	- eclipsestweakeroo 0.4.6-beta.2-1.21
	- emi 1.1.10+1.21+fabric
	- enchantingcommands 3.3
	- enchantingtree 1.0.0
	- enchlevel-langpatch 2.2.6
	- endportalrecipe 5.4
	- enhancedblockentities 0.10.1+1.21
	- expanded_weapon_enchanting 1.0.8
	- explorerscompass 1.21-2.2.5-fabric
	- extended_drawers 3.0.2+mc.1.21
	   |-- config_toolkit 1.1.1
	   |    |-- io_determann_shadow-api-17 0.2.0
	   |    \-- net_fabricmc_javapoet 0.1.0
	   \-- graphlib 2.0.0+1.21
	        |-- codextra 2.0.0+1.21
	        \-- common_events 1.0.0+1.21
	- fabric-api 0.100.6+1.21
	   |-- fabric-api-base 0.4.42+6573ed8cd1
	   |-- fabric-api-lookup-api-v1 1.6.67+b5597344d1
	   |-- fabric-biome-api-v1 13.0.28+6fc22b99d1
	   |-- fabric-block-api-v1 1.0.22+0af3f5a7d1
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8cd1
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a7d1
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8cd1
	   |-- fabric-command-api-v1 1.2.49+f71b366fd1
	   |-- fabric-command-api-v2 2.2.28+6ced4dd9d1
	   |-- fabric-commands-v0 0.2.66+df3654b3d1
	   |-- fabric-content-registries-v0 8.0.14+b5597344d1
	   |-- fabric-convention-tags-v1 2.0.17+7f945d5bd1
	   |-- fabric-convention-tags-v2 2.4.1+86024ea6d1
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a7d1
	   |-- fabric-data-attachment-api-v1 1.1.24+6a6dfa19d1
	   |-- fabric-data-generation-api-v1 20.2.11+16c4ae25d1
	   |-- fabric-dimensions-v1 4.0.0+6fc22b99d1
	   |-- fabric-entity-events-v1 1.6.12+6fc22b99d1
	   |-- fabric-events-interaction-v0 0.7.10+e633f883d1
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd9d1
	   |-- fabric-item-api-v1 11.0.0+afdfc921d1
	   |-- fabric-item-group-api-v1 4.1.2+78017270d1
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a7d1
	   |-- fabric-keybindings-v0 0.2.45+df3654b3d1
	   |-- fabric-lifecycle-events-v1 2.3.11+8f3583aed1
	   |-- fabric-loot-api-v2 3.0.12+3f89f5a5d1
	   |-- fabric-loot-api-v3 1.0.0+3f89f5a5d1
	   |-- fabric-message-api-v1 6.0.13+6573ed8cd1
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6bd1
	   |-- fabric-networking-api-v1 4.2.0+ab7edbacd1
	   |-- fabric-object-builder-api-v1 15.1.12+d1321076d1
	   |-- fabric-particles-v1 4.0.2+6573ed8cd1
	   |-- fabric-recipe-api-v1 5.0.10+65089712d1
	   |-- fabric-registry-sync-v0 5.0.24+6ced4dd9d1
	   |-- fabric-renderer-api-v1 3.3.0+0ae0b97dd1
	   |-- fabric-renderer-indigo 1.6.5+48fb1586d1
	   |-- fabric-renderer-registries-v1 3.2.67+df3654b3d1
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2ed1
	   |-- fabric-rendering-fluids-v1 3.1.6+b5597344d1
	   |-- fabric-rendering-v0 1.1.70+df3654b3d1
	   |-- fabric-rendering-v1 5.0.4+5a8c785ed1
	   |-- fabric-resource-conditions-api-v1 4.2.1+d153f344d1
	   |-- fabric-resource-loader-v0 1.1.5+78017270d1
	   |-- fabric-screen-api-v1 2.0.24+b5597344d1
	   |-- fabric-screen-handler-api-v1 1.3.81+b5597344d1
	   |-- fabric-sound-api-v1 1.0.23+6573ed8cd1
	   |-- fabric-transfer-api-v1 5.1.15+3dccd343d1
	   \-- fabric-transitive-access-wideners-v1 6.0.12+6573ed8cd1
	- fabric-language-kotlin 1.11.0+kotlin.2.0.0
	   |-- org_jetbrains_kotlin_kotlin-reflect 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 2.0.0
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 2.0.0
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.24.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.1
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- faster-random 4.1.0
	- ferritecore 7.0.0
	- frozenlib 1.7.4-Fabric+1.21
	- ftblibrary 2100.1.2
	- ftbultimine 2100.1.0
	- furnacerecycle 2.4
	- geckolib 4.5.6
	- globalpacks 21.0.0
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- globalxp 1.11.1
	- grabbymobs 1.5
	- grassseeds 3.2
	- grindenchantments 3.2.2+1.21-rc1
	   \-- codec-config-api 2.0.0+1.20.5-rc3
	- healingcampfire 6.0
	- ichunutil 1.0.0
	- indium 1.0.34+mc1.21
	- infinite-music 0.4.3
	- infinite_fluid_bucket 0.5.0
	- ingameime 1.1.0-xplus-1.21
	- inventoryprofilesnext 2.0.1
	- jade 15.1.3+fabric
	- java 21
	- jjelytraswap 2.1
	- kotori316_version_checker 2.4.0
	- kotori_scala 3.0.0
	   |-- org_scala-lang_scala-library 2.13.12
	   |-- org_scala-lang_scala3-library_3 3.3.3
	   |-- org_typelevel_cats-core_3 2.10.1-kotori
	   |-- org_typelevel_cats-free_3 2.10.1-kotori
	   \-- org_typelevel_cats-kernel_3 2.10.1-kotori
	- libipn 5.0.2
	- libjf 3.16.0
	   |-- libjf-base 3.16.0
	   |-- libjf-config-commands 3.16.0
	   |-- libjf-config-core-v2 3.16.0
	   |-- libjf-config-network-v0 3.16.0
	   |-- libjf-config-ui-tiny 3.16.0
	   |-- libjf-data-manipulation-v0 3.16.0
	   |-- libjf-data-v0 3.16.0
	   |-- libjf-mainhttp-v0 3.16.0
	   |-- libjf-translate-v1 3.16.0
	   |-- libjf-unsafe-v0 3.16.0
	   \-- libjf-web-v1 3.16.0
	- litematica 0.18.999-sakura.14
	- lmft 1.0.4+1.21
	- malilib 0.19.999-sakura.6
	- midnightlib 1.5.7
	- minecraft 1.21
	- minihud 0.31.999-sakura.3
	- minimalism_leaf_decay 0.1.0
	- modmenu 11.0.1
	- monolib 1.3.0
	- naturescompass 1.21-2.2.6-fabric
	- nerb 0.4
	- no-shield-delay 1.0.0
	- noexpensive 1.21-1.9.0
	- nohostilesaroundcampfire 7.0
	- norealmsbutton 1.1.0
	- owo 0.12.10+1.21
	   |-- io_wispforest_endec 0.1.0
	   |-- io_wispforest_endec_gson 0.1.0
	   |-- io_wispforest_endec_jankson 0.1.0
	   \-- io_wispforest_endec_netty 0.1.0
	- passivesearchbar 1.0.0
	- passiveshield 3.5
	- peek 1.21-1.3.2
	- persistent-stuff 1.2.0
	- placeholder-api 2.4.0+1.21
	- potpourri 1.0
	- quad 1.2.7
	- randombonemealflowers 4.5
	- randomsheepcolours 3.3
	- reacharound 1.3.0
	- reborncore 5.11.7
	   \-- team_reborn_energy 4.1.0
	- reinfbarrel 2.5.1+1.21
	   \-- reinfcore 4.0.1+1.21
	- reinfchest 3.0.1+1.21
	   \-- reinfcore 4.0.1+1.21
	- reputation 0.2.6+jade.1.21
	- slyde 1.7.5
	- sodium 0.5.11+mc1.21
	- stack-to-nearby-chests 0.5.8
	   \-- libgui 11.0.0+1.21
	        |-- jankson 8.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- taxfreelevels 1.3.12
	- text-formatting-everywhere 1.0.1
	- tomereader 0.0.4
	- toms_storage 2.0.6
	   |-- cardinal-components-base 6.1.0
	   \-- cardinal-components-block 6.1.0
	- too-many-shortcuts 0.0.1+mc.1.21
	- too-many-shortcuts-api 0.0.1+mc.1.21
	- transcendingtrident 4.7
	- trashslot 21.0.2
	- travelersbackpack fabric-1.21-10.0.4
	- travelerscompass 3.0.4
	- trifle 0.26.1
	- trimeffects 1.3.1
	- trinkets 3.10.0
	   |-- cardinal-components-base 6.1.0
	   \-- cardinal-components-entity 6.1.0
	- tweakermore 3.19.0
	   |-- conditional-mixin 0.6.2
	   \-- mixinextras 0.3.5
	- tweakeroo 0.20.999-sakura.9
	- waystones 21.0.7
	- woodenbucket 1.21-4.0.0.0
	- woodenshears 1.21-3.1.1.0
	- xaerominimap 24.2.1
	- xaeroplus 2.15
	   |-- com_github_ben-manes_caffeine_caffeine 3.1.8
	   \-- net_lenni0451_lambdaevents 2.4.2
	- xaeroworldmap 1.38.8
	- yeetusexperimentus 87.0.0
	- yet_another_config_lib_v3 3.5.0+1.21-fabric
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- zero-tick-crops 1.0.0+1.20.5+

### Server

Not tested

### Client

Happens

### Logs

https://gist.github.com/Phoupraw/65eee0a6b23efb0cf0a1feafcad514c8

**Comment by MattiDragon** [comment]
Seems like I rounded too early when calculating the capacity of a drawer. Because 99 is larger than the 64 i previously assumed was max, the number I divide the capacity by ends up less than 1. Because I rounded down before dividing the capacity by it, I ended up dividing by 0. Will be fixed soon.
