### ISSUE TITLE
[Bug] Crafter can't input into drawer

### ISSUE THREAD

**Issue by RedSnt** [MattiDragon/ExtendedDrawers#124]
### Description of the issue

The expected outcome of pointing the output of a crafter from 1.21 into a drawer would be to deposit it like it was a chest. Instead the crafter just spits the output on the ground before the drawer doesn't accept it.

### Reproduction steps

Point crafter's output end into drawer. Activate crafter. 

### Mod version

3.0.2

### Operating System

Linux (flatpak version via prism launcher v.8.4)

### Minecraft version

1.21

### Other mods

Fabric 0.16.0

### Server

Not tested

### Client

Happens

### Logs

https://gist.github.com/RedSnt/62afc16893193d1df4e3976e4b3afc5a

### Extra Context

I'm circumventing this by having the crafter output into a hopper, and said hopper then outputs into the drawer.

**Comment by MattiDragon** [comment]
I'll look into this, although I suspect this is an issue with fabric api not special casing the crafter

**Comment by MattiDragon** [comment]
This is a fabric api bug and has been reported there

**Comment by RedSnt** [comment]
Thanks. Should I close this then?

**Comment by MattiDragon** [comment]
> Thanks. Should I close this then?

I'd keep it open so that anyone else encountering the issue knows about it

**Comment by MattiDragon** [comment]
Fixed in the latest fapi release
