### ISSUE TITLE
[Bug]: Drawers don't update comparators

### ISSUE THREAD

**Issue by Qwyntex** [MattiDragon/ExtendedDrawers#125]
### Description of the issue

Pretty much exactly the same as in #39 except that it does that with every drawer.
When placing items in drawers while having a comparator read the drawer value the read value doesn't change until manually updating the comparator

### Reproduction steps

Place drawer
Put items in drawer
place comparator facing the drawer and add a line of redstone before doing anything with the drawer
put more items in the drawer
the output doesn't change until you update the comparator block

### Mod version

2.1.1+mc.1.20.1

### Operating System

Arch Linux

### Minecraft version

1.20.1

### Other mods

no mods required

### Server

Happens

### Client

Happens

### Logs

no output

### Extra Context

According to your commits you have removed comparator support for shadow drawers because of weird issues and I have not found that you put it back in, indeed testing it it seems that they do not have support for comparators. Instead you stated that now the accesspoint supports it, however it produces the, presumably, same weird behaviour as the shadow drawers before. So do the normal drawers. 
It seems as if the drawer don't update redstone components nor do they update other blocks when accessed. The latter may be intententional though as the vanilla minecraft chest doesn't do that either.

**Comment by MattiDragon** [comment]
The weird behavior with shadow drawers is because it's non-trivial to find the total capacity for a single item. The same shouldn't cause issues elsewhere. It's possible that I've forgotten to update comparators somewhere along the way

**Comment by Qwyntex** [comment]
perfect, thank you
