### ISSUE TITLE
[Crash]: Error: java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by Survivalist90** [MattiDragon/ExtendedDrawers#129]
### Description of the issue

After installing the Mod, everything went fine. It crashed and destroyed an enchanted Tool, nothing to worry. 
But now I started to build some drawer extensions, what again, worked fine. 
After placing the first extension on a drawer, the game crashed, and refuses to load again, showing me the same Crash. 
Seems like it has some problems rendering the block, and showing me the; 
Error: java.lang.NullPointerException: Rendering Block Entity

If someone knows about that issue, and a soulution, without dropping the mod, I would be pleased. 

### Reproduction steps

1. Build a drawer extension 
2. Place it on the front of your drawer
3. Game crashes

### Mod version

Extended-Drawers-Mod-Fabric-Quilt-1.21

### Operating System

Windows 10 

### Minecraft version

1.21

### Other mods

fabric-api-0.101.2+1.21, Extended-Drawers-Mod-Fabric-Quilt-1.21

### Server

Not tested

### Client

Not tested

### Logs

https://pastebin.com/3h55a86Y

### Crash Report

https://pastebin.com/ZbyTwqux

### Extra Context

I have a few furniture Mods, hope its nothing between them.

**Comment by MattiDragon** [comment]
You have a sodium version below 0.6 without also having indium installed. Extended drawers requires a fabric api feature that sodium used to not support. To fix the crash either install indium or update to the sodium 0.6 beta (however this will break upgrade icon rendering until I get around to implementing a workaround)

**Comment by Survivalist90** [comment]
> You have a sodium version below 0.6 without also having indium installed. Extended drawers requires a fabric api feature that sodium used to not support. To fix the crash either install indium or update to the sodium 0.6 beta (however this will break upgrade icon rendering until I get around to implementing a workaround)

Install Indium or update... I got it... 
Do you know the issue or did you use the files attached? 
Just curious tho 😉
