### ISSUE TITLE
[Feature]: "New item funnel": network storage piece that dumps new items into a chest.

### ISSUE THREAD

**Issue by Geethebluesky** [MattiDragon/ExtendedDrawers#13]
### Description of the feature

I don't have a catchy name for it, sorry. But it would be nice to be able to funnel unrecognized items in a network into a specific place where I know to find them, instead of having the new item randomly land in an unused drawer "somewhere". My network tends to have A LOT of empty drawers because I know in advance which mods I play with, so I build the whole thing in advance. Then I know which items I can eventually expect and where I'll eventually put them, but until I find those items in game they don't have a specific place in any drawer.

The mod knows to put items in empty drawers if it can't find an existing stack, and shadow drawers lets us find something in the network, so I assume the mod already makes it possible to relocate items that don't already have a drawer to a specific place.

That "funnel" could dump into a chest, a hopper etc. to let the user decide the end storage for new items.

(Optional: It'd be even nicer if we could filter the piece according to specific mods but I don't know how complicated that would be, for example new stuff from Botania goes through funnel X, new stuff from vanilla MC goes intom funnel Y...)

### How does it make the mod better?

Means players can decide where new items end up without having to check drawers to find all the stuff (or wonder why some random item got placed in a random spot)

Players can empty their pockets into the network after exploring and get to see what new stuff they found after the access point's done filtering... (I tend to have backpacks full of new blocks/items, I empty those into a chest, chest feeds into hopper, hopper feeds into access point, access point slowly sorts everything --> new items get put aside for me to sort properly *later* instead of taking up space everywhere)

Get to spend more time playing and less time sorting. :)

**Comment by MattiDragon** [comment]
I see the benefit of this, but I'm not sure if it fits the mod. Also, I recommend using AE for managing large systems, as it has a nice gui and a lot of other features.

**Comment by Geethebluesky** [comment]
I was hoping to keep this modpack to just Botania though but I understand if the above isn't something you want overall!

I've never used AE, but it looks like it provides some interesting interactions with Botania either way so maybe I'll give it a try.

**Comment by tallytarik** [comment]
I've just started using this mod and have loved it so far, but I think this would be a great feature!

A workaround I'm using at the moment is to make sure existing drawers are filled with a dummy item, and put some empty 'overflow' drawers in a hidden spot, with hoppers pulling all of their items into an overflow chest. 

(As an aside, it'd be nice to be able to use the lock on an empty drawer to keep it empty - at the moment, an empty locked drawer will get filled if you put something in an access point that doesn't exist in the system - maybe a different feature request!)

**Comment by MattiDragon** [comment]
> (As an aside, it'd be nice to be able to use the lock on an empty drawer to keep it empty - at the moment, an empty locked drawer will get filled if you put something in an access point that doesn't exist in the system - maybe a different feature request!)

I'd consider that a bug. Manually inserting should work on locked drawers, but it doesn't make sense for the access point to use empty ones

**Comment by MattiDragon** [comment]
Closing this for now. I'll reopen if I ever reconsider this idea
