### ISSUE TITLE
[Feature]: VOID UPGRADE

### ISSUE THREAD

**Issue by msaikat702** [MattiDragon/ExtendedDrawers#131]
### Description of the feature

The VOID UPGRADE will delete items when the drawer gets full of those items.
The void upgrade Recipe could be an Upgrade template surrounded by 4 sticks in all corners and 4 obsidian in other places.

### How does it make the mod better?

The void upgrade will help us to make automation easy for us because making create mod farms some things need to be deleted after having some amount of it, like Saplings, Seeds, and sticks.
Without the void upgrade, it's tricky to control those things because those things will take other unlocked drawers and also block Chutes (from create mod), and hoppers with those unwanted items and make the firm unusable after a short period.

**Comment by MattiDragon** [comment]
Voiding is already supported as a toggle on drawers. Sneak-click with a lava bucket to enable voiding mode
