### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RacinanteOpus** [MattiDragon/ExtendedDrawers#132]
### Description of the issue

Fluid storage priority may result in game crash.

### Reproduction steps

1. Create setup as shown in the image.  Second column is an "external storage" connecter, Grid and creative controller, third column is a cauldron, importer, and disk drive with a 4k fluid disk, then an exporter and cauldron.
2. Set priority of disk drive to -5.
3. Access exporter and right click the top left slot with a lava bucket (to filter on lava).  Add lava to empty caudron attached to importer.  Remove lava from rightmost cauldron.  At some point in this process, the game will crash.

My suspicion is that the fabric transfer api is attempting to put the lava into extended drawers, and extended drawers both cannot store it and is not rejecting it.

### Mod version

3.0.3+mc.1.21

### Operating System

Windows 10 and Ubuntu linux 18.0.4

### Minecraft version

1.21

### Other mods

Fabric API 0.102.0
Refined Storage 2.0.0-milestone 4.7

### Server

Not tested

### Client

Happens

### Logs

https://pastebin.com/jEvxN4AF

### Extra Context

![BugConfig](https://github.com/user-attachments/assets/2b4e21af-1893-4e93-a108-18d52cf9ac30)

**Comment by MattiDragon** [comment]
@raoulvdberge
This is almost certainly a bug on the RS2 side. You're asking to extract `null` from a drawer (which isn't allowed by transfer api), and I can't find any way for that null to have come from my code. It seems to me that the null is originating from [here](https://github.com/refinedmods/refinedstorage2/blob/91a274fe48b4a85852dc860856d1eabc329000fb/refinedstorage-fabric/src/main/java/com/refinedmods/refinedstorage/fabric/ModInitializerImpl.java#L222) and isn't handled [here](https://github.com/refinedmods/refinedstorage2/blob/91a274fe48b4a85852dc860856d1eabc329000fb/refinedstorage-fabric/src/main/java/com/refinedmods/refinedstorage/fabric/storage/FabricStorageExtractableStorage.java#L60).

**Comment by raoulvdberge** [comment]
I fixed it on my end. Thank you @MattiDragon  and @RacinanteOpus
