### ISSUE TITLE
[Crash]: When Breaking

### ISSUE THREAD

**Issue by TheWanderingTrader** [MattiDragon/ExtendedDrawers#134]
### Description of the issue

Players are crashing client side when breaking acompacting drawre

### Reproduction steps

Break a compacting drawer

### Mod version

3.0.3+mc.1.21

### Operating System

Win 10/11

### Minecraft version

1.21

### Other mods

Many

### Server

Doesn't happen

### Client

Happens

### Logs

https://mclo.gs/fAzrRTx

### Crash Report

https://mclo.gs/fAzrRTx

**Comment by MattiDragon** [comment]
this is fixed in v3.0.4
