### ISSUE TITLE
[Bug]: Comparator Redstone Output from Drawer Access Point doesn't Update

### ISSUE THREAD

**Issue by Shadowdane** [MattiDragon/ExtendedDrawers#136]
### Description of the issue

Placing a comparator on a drawer access point to get a redstone signal on how full the storage is doesn't actually update when new items are input into the Drawers or Access point.

### Reproduction steps

1. Place Drawer Access Point
2. Place Comparator facing the Drawer Access Point
3. Place 1 or more Drawers and fill them with items
4. The Comparator will not power or show any signal strength change
5. If you attach a lever or any other redstone power source and update the redstone state on the Access Point then the Comparator will update.
6. Adding or removing items from Drawers will not change the state of the Comparator.

![2024-10-18_18 48 10](https://github.com/user-attachments/assets/fff41d40-93e5-4305-9b6b-6c336b3eaed1)

After flipping the lever up and down, the Comparator will update and show a redstone signal.   
![2024-10-18_18 48 28](https://github.com/user-attachments/assets/8836d2e3-b9b7-4a61-bba6-f93014e73610)

### Mod version

3.0.4

### Operating System

Windows 11

### Minecraft version

1.21.1

### Other mods

Fabric API v0.105.0

### Server

Happens

### Client

Happens

### Logs

Logs not needed, there are no errors in the log.

**Comment by MattiDragon** [comment]
Will be fixed in the next update
