### ISSUE TITLE
[Crash]: Compacting drawer with free slot

### ISSUE THREAD

**Issue by yuma-dev** [MattiDragon/ExtendedDrawers#139]
### Description of the issue

When you have a compacting drawer with for example coal, the bottom left slot is free and crashes when you left click it.

### Reproduction steps

1. Compacting drawer with coal
2. Leftclick empty slot

### Mod version

3.0.3

### Operating System

Win11

### Minecraft version

1.21

### Other mods

Fabric API: 0.102.0

### Server

Doesn't happen

### Client

Happens

### Logs

https://mclo.gs/h2mkOtV

### Crash Report

https://mclo.gs/ui1hqTe

**Comment by MattiDragon** [comment]
Please try again with v3.0.4. This issue was previously reported and fixed there

**Comment by yuma-dev** [comment]
thats only for 1.21.1, i dont see 3.0.4 for 1.21 anywhere

**Comment by MattiDragon** [comment]
Why are you still on 1.21? Pretty much everything should work on 1.21.1. If it doesn't you can probably run the ED v3.0.4 on 1.21 with a dependency override. If that doesn't work, then you're out of luck, as I don't provide any updates for 1.21 as its mostly obsolete
