### ISSUE TITLE
[Feature]: Upward facing drawers

### ISSUE THREAD

**Issue by andersmmg** [MattiDragon/ExtendedDrawers#14]
### Description of the feature

The ability to face drawers up would be nice for some builds

### How does it make the mod better?

I want it as I'm going for a kind of market look with 'bins' of produce.

**Comment by MattiDragon** [comment]
When originally implementing the mod I was thinking about this, but realized that it's too complicated:

* What direction should the text face?
  * Constant would be painful to build with
  * Changeable would be a lot of block states while also a pain to build with 
* The the code for rotating the display would be way more complicated

**Comment by MattiDragon** [comment]
They are a pain to implement well and figuring out a good placement system is hard. May or may not happen.

**Comment by MattiDragon** [comment]
I have decided to finally implement this. Progress is looking good
