### ISSUE TITLE
[Bug] Cannot attach corporea sparks to drawers, or drawer access points

### ISSUE THREAD

**Issue by gchpaco** [MattiDragon/ExtendedDrawers#18]
### Description of the issue

I expected to be able to put a Botania corporea spark on a drawer, or a drawer access point.  I persistently cannot do so, regardless of facing on the block.

### Reproduction steps

1. Get Botania corporea spark
2. Attempt to attach it to a drawer (shift+right click)
Note that this does work for the Storage Drawers mod.

### Mod version

1.3.1+mc1.18.2

### Operating System

macOS Monterey

### Minecraft version

1.18.2

### Other mods

Botania 1.18.2-434-FABRIC

### Server

Happens

### Client

Happens

### Logs

No log messages

**Comment by MattiDragon** [comment]
I suspect this is due to botania not supporting the fabric transfer api

**Comment by MattiDragon** [comment]
Could you report this to botania? I don't have enough knowledge of how the mod works to try and find the problem. Tell them that I only support fabric transfer api and not the vanilla `Inventory` api.

**Comment by MattiDragon** [comment]
This is an issue on botanias side. You'll have to wait for them to fix it

**Comment by gchpaco** [comment]
Okay, thanks.

**Comment by Baughn** [comment]
This now works with single-compartment drawers. 

However, if a corporeal spark is attached to a multi-compartment drawer then it consistently crashes the server with a CME whenever it attempts to pull anything out of it.

**Comment by MattiDragon** [comment]
> it consistently crashes the server with a CME whenever it attempts to pull anything out of it.

:concern:
@Baughn, could you send the logs/crash report?

Edit: could you open a new bug report, it's a separate issue after all

**Comment by MattiDragon** [comment]
The main issue was fixed a while back and there will be a workaround for the crash issue in the next update. The underlying botania bug hasn't been fixed however.
