### ISSUE TITLE
[Bug]: Can't insert into an access point with a Create funnel

### ISSUE THREAD

**Issue by object-Object** [MattiDragon/ExtendedDrawers#19]
### Description of the issue

When a Create funnel (tested with Brass, probably also happens with Andesite) is placed on a Drawer Access Point, the funnel is unable to insert items into the access point. Funnels work properly on individual drawers, just not the access point.

### Reproduction steps

1. Place a drawer beside an access point.
2. Shift-place a Create funnel on the access point so that it's pointing into the access point.
3. Throw an item at the funnel and watch it not go in.

### Mod version

v1.3.1+mc.1.18.2

### Operating System

Windows 11 Home 10.0.22000

### Minecraft version

1.18.2

### Other mods

Create v0.5.0c-708

### Server

Happens

### Client

Not tested

### Logs

N/A

**Comment by MattiDragon** [comment]
Odd. I'll try debugging tomorrow. Btw you should update to 1.3.2 to fix a item deletion bug

**Comment by MattiDragon** [comment]
This is an issue on creates end. I've reported it to them

**Comment by andrenasturas** [comment]
Looks like it is fixed now.
Tested in 1.19.2 with Create Fabric 0.5.0i and ExtendedDrawers 1.3.6.

![Two separate extended drawers networks, one feeding the other by dropping blocks from an access point via an outbound Create andesite funnel to an other access point via an inbound Create brass funnel](https://i70.servimg.com/u/f70/11/34/80/05/2023-012.png)
