### ISSUE TITLE
[Crash]: Crash under Quilt

### ISSUE THREAD

**Issue by JieningYu** [MattiDragon/ExtendedDrawers#20]
### Description of the issue

Crash under Quilt

### Reproduction steps

1. Install QSL/QFAPI with this mod under Quilt Loader
2. Crash

### Mod version

1.3.2+mc1.18.2

### Operating System

macOS 12.5 Beta (21G5027d)

### Minecraft version

1.18.2

### Other mods

Quilted Fabric API: 0.56.0-1.18.2
Quilt Standard Libraries: 1.0.0-beta22

### Server

Not tested

### Client

Happens

### Logs

https://paste.mozilla.org/sy70bAOh/raw

### Crash Report

https://paste.mozilla.org/sy70bAOh/raw

**Comment by MattiDragon** [comment]
For some reason quilt isn't loading graphlib from inside extended drawers. You can manually get it here: https://github.com/Kneelawk/GraphLib/releases/tag/v0.2.4%2B1.18.2

**Comment by MattiDragon** [comment]
Found out why. Will release a fix shortly.
