### ISSUE TITLE
[Bug]: Drawer Access Point doesn't work properly

### ISSUE THREAD

**Issue by alpha-pvp** [MattiDragon/ExtendedDrawers#21]
### Description of the issue

It seems that the access point isn't compatible with the storage bus from AE2.
If I connect it to a single drawer it works, but not with the access point.
Tom's Simple Storage seems to have the same issue with the mod.

### Reproduction steps

1. Place Drawer Access Point
2. Place Drawer containing items next to it
4. Attach AE2 Storage Bus
5. Check ME Terminal

### Mod version

1.3.3

### Operating System

Windows 11

### Minecraft version

1.18.2

### Other mods

Fabric API: 0.58.0

### Server

Not tested

### Client

Happens

### Logs

-

**Comment by MattiDragon** [comment]
See #9
