### ISSUE TITLE
[Feature]: Drawer Tooltips

### ISSUE THREAD

**Issue by bendrick92** [MattiDragon/ExtendedDrawers#22]
### Description of the feature

It would be great to have the option to see what specific block is in a given drawer slot by hovering over it. As it is, similar looking blocks can make it confusing to know which drawer has which block type.

### How does it make the mod better?

Would improve the usability and efficiency of extracting items in drawers, especially differentiating similar-looking blocks.

**Comment by MattiDragon** [comment]
How would it be shown?

**Comment by bendrick92** [comment]
Something similar to how What Are We Looking At works?

WAWLA: [https://www.curseforge.com/minecraft/mc-mods/wawla](https://www.curseforge.com/minecraft/mc-mods/wawla)

![WAWLA mod example](https://user-images.githubusercontent.com/7011962/188676027-d850d967-0cd8-4dcc-bdc9-af5900f9540c.png)

**Comment by MattiDragon** [comment]
I would just recommend picking a HUD mod that properly supports the transfer api. That way drawer contents will show up. I think the fabric port of the one probe does it. It might not have names tho

**Comment by bendrick92** [comment]
Thanks for the suggestion! After looking into One Probe, it does seem like it would support showing the contents of the drawers, unfortunately as you mentioned there are no text labels (the key feature I'm looking for):

## One Probe

![image](https://user-images.githubusercontent.com/7011962/189537411-a0a22a86-99b1-4d2d-9729-d901430bb45b.png)

The [Drawers Tooltip](https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip) mod does this better, but doesn't appear to be available for Fabric:

## Drawers Tooltip

![image](https://user-images.githubusercontent.com/7011962/189537360-8b039697-8696-4355-a901-c4cfa15946b8.png)

**Comment by MattiDragon** [comment]
I have content tooltips in the inventory

**Comment by Seceroth** [comment]
I think what would work is properly showing it in this tooltip:
![Knipsel](https://user-images.githubusercontent.com/20866237/190836525-5d8361e1-b2be-4c80-87ec-6c2d02c5b752.PNG)
That's four different seeds. Can't really tell what is what without removing them. Using WTHIT for the display.

**Comment by MattiDragon** [comment]
> I think what would work is properly showing it in this tooltip:
> That's four different seeds. Can't really tell what is what without removing them. Using WTHIT for the display.

I'd just go tell the wthit or megane devs to properly support the transfer api. I'd rather not add integration just because an other mod can't handle standard ways of doing things

**Comment by MattiDragon** [comment]
I'll close this as I feel the parts of this that extended drawers should provide (tooltips in item form) already exist in the mod. Feel free to open a new issue if you have anything specific you want to request.
