### ISSUE TITLE
[Bug]: Drawers don't stack after being placed

### ISSUE THREAD

**Issue by Xandaros** [MattiDragon/ExtendedDrawers#27]
### Description of the issue

An empty drawer freshly crafted and an empty drawer previously placed don't stack with each other. I would expect an empty, unupgraded drawer to always stack with other empty and unupgraded drawers, freshly crafted or not.

### Reproduction steps

See description

### Mod version

v1.3.3

### Operating System

Linux

### Minecraft version

1.18.2

### Other mods

Cabricality modpack... but I doubt it matters

### Server

Happens

### Client

Not tested

### Logs

Irrelevant

**Comment by awilliamson** [comment]
Can confirm, NBT Tag gets added on place, freshly crafted have no tags. :+1:

**Comment by MattiDragon** [comment]
I'll have to see if I can do something about this, but in the mean time you can just place and break all drawers
