### ISSUE TITLE
[Bug]: EasyAutoCrafting multiblock - Droppers do not insert into drawers + access points

### ISSUE THREAD

**Issue by stinkysmellystinkysmelly** [MattiDragon/ExtendedDrawers#31]
### Description of the issue

Seems to be a compatibility issue between Extended Drawers and EasyAutoCrafting (https://github.com/FakeDomi/EasyAutoCrafting)

### Reproduction steps

Using EasyAutoCrafting, create an auto-crafting machine with the dropper (output) facing a drawer block that should be able to take an input from a dropper
Redstone pulse the crafting machine to perform a craft
Observe as dropper drops the item rather than inserting

### Mod version

1.3.4

### Operating System

Windows 10 + Ubuntu 20.04 (Tested on a server and offline)

### Minecraft version

1.19.2

### Other mods

Minecraft 1.19.2
Quilt 1.17.5-beta.3
Modlist
Quilted Fabric API 4.0.0-beta.13+0.62
Extended Drawers 1.3.4
EasyAutoCrafting 1.6

### Server

Happens

### Client

Happens

### Logs

https://pastebin.com/m6NhKhx9

**Comment by MattiDragon** [comment]
Fixed on their side. Don't know about the release schedule. Closing issue
