### ISSUE TITLE
[Bug]: Nested drawers allow for 'infinite' storage

### ISSUE THREAD

**Issue by Infinidoge** [MattiDragon/ExtendedDrawers#32]
### Description of the issue

Drawers can be put inside drawers, allowing you to (inconveniently) have 'infinite' space by nesting drawers within each other.
This could also lead to reaching the maximum packet size by nesting a lot of full drawers within each other

### Reproduction steps

1. Take a drawer, fill it with items
2. Break that drawer
3. Insert that drawer into another drawer

### Mod version

v1.3.4

### Operating System

Linux (NixOS 22.11/Unstable, Linux 6.0.2)

### Minecraft version

1.19.2

### Other mods

Quilt 0.17.6
Quilted Fabric API 4.0.0-beta.9

### Server

Not tested

### Client

Happens

### Logs

No log output produced

### Extra Context

Most of the issue form isn't really necessary since this seems to be more of a design oversight than a proper 'bug'.

**Comment by MattiDragon** [comment]
The solution is probably marking drawers as a container and disallowing containers in them. This does prevent drawers from being put in shulkers and vice versa, but that's probably good
