### ISSUE TITLE
[Feature]: Be able to break drawers from the front

### ISSUE THREAD

**Issue by Mondanzo** [MattiDragon/ExtendedDrawers#35]
### Description of the feature

Some sort of way to break drawers from the front, be it using a specific item like the lock to break or a keybind. Just a way to break them without having to dig your way to the side of them.

### How does it make the mod better?

Having this sort of drawer walls just looks rad! But trying to reorganise it when you want to keep stone to stone later on or move other items higher up is a pain without being able to break them from the beginning.
![image](https://user-images.githubusercontent.com/14519085/209922468-4215b770-045f-4e3c-8d9d-fba10d745c6f.png)

**Comment by MattiDragon** [comment]
Are you in creative or survival mode? In creative there's a config option for how breaking works, in survival you should just be able to hold to break

**Comment by Mondanzo** [comment]
I'm in survival and holding doesn't work. At least Jade doesn't show me that I'm gaining progress and after 10 seconds with a gold axe it's still not broken.

**Comment by Mondanzo** [comment]
playing with Version 1.3.5 on 1.19.2
