### ISSUE TITLE
[Bug]: In Game Guidebook not available

### ISSUE THREAD

**Issue by TriangleSteve** [MattiDragon/ExtendedDrawers#42]
### Description of the issue

The in-game guidebook that you mention is not available in-game, it can't be crafted or grabbed from creative mode.

### Reproduction steps

Create new creative world
Collect upgrade frame and book
Try to combine on crafting table or in inventory

### Mod version

v1.3.6

### Operating System

Windows 10

### Minecraft version

1.19.2

### Other mods

Fabric API 0.73.0

### Server

Not tested

### Client

Happens

### Logs

N/A

**Comment by MattiDragon** [comment]
You need to install patchouli for it to work
