### ISSUE TITLE
[Crash]: Game crashed while inserting drawer upgrade II in a quad-drawer

### ISSUE THREAD

**Issue by andremedeiros99** [MattiDragon/ExtendedDrawers#43]
### Description of the issue

I was setting up my storage system with quad-drawers and tried to upgrade one of them with the drawer upgrade II (the iron one) and the game crashed, the log says it's a rendering block entity issue, could also be a sodium issue by looking at the logs

### Reproduction steps

1. place a few quad-drawers connected to each other
2. place a interface in the middle
3. upgrade one of them with drawer upgrade II

### Mod version

1.3.6

### Operating System

Windows 10

### Minecraft version

1.19.3

### Other mods

Carry On 2.0.4.15
Cloth Config v9 9.0.94
EntityCulling-Fabric 1.6.0-mc1.19.3
Extended Drawers 1.3.6+mc.1.19.3
Fabric API 0.73.0+1.19.3
Fabric Language Kotlin 1.9.0+kotlin.1.8.0
Fabric Loader 0.14.14
Iris 1.5.1
Iron Chests 1.7.8
JamLib 0.6.0+1.19.3
MidnightLib 1.1.0
oωo 0.9.3+1.19.3
Patchouli 1.19.3-78-FABRIC
Reese's Sodium Options 1.4.9+mc1.19.2-build.67
Right Click Harvest 3.1.0+1.19.3
Sodium 0.4.8+build.22

### Server

Not tested

### Client

Happens

### Logs

https://pastebin.com/1hpyT7vj

### Crash Report

https://pastebin.com/WfP6gt37

**Comment by MattiDragon** [comment]
You have sodium, but not indium. Install indium to fix compat
