### ISSUE TITLE
[Feature]: Config option to allow quad drawers in shulker boxes

### ISSUE THREAD

**Issue by Sammcb** [MattiDragon/ExtendedDrawers#44]
### Description of the feature

Would love to see a config option added that allows drawers to be placed in shulker boxes. (Could be `false` by default).

### How does it make the mod better?

This would really help when I want to move my storage room. Currently, it's really tedious because I have to store them all in my inventory.

**Comment by MattiDragon** [comment]
Seems like a good idea

**Comment by Sammcb** [comment]
Thanks so much for adding this so quickly!
