### ISSUE TITLE
[Feature]: Ability to remove upgrades from drawers to allow them to stack when not in use

### ISSUE THREAD

**Issue by bstrawsma** [MattiDragon/ExtendedDrawers#45]
### Description of the feature

So first of love the mod so far, how ever I feel like there would be a lot of good for being able to remove the upgrades from the drawers when you are planning on not using them or transporting them. Maybe something like the lock item where you can craft a tool to remove upgrades you are not wanting. Currently the only way to remove an upgrade is to swap it with another as far as I am aware.

### How does it make the mod better?

When trying to store the drawers if not in use or to transport even if there is no blocks in the inventory the upgrade gives it a custom nbt data that doesn't let it stack with other newly crafted drawers. This would allow players to remove upgrades on drawers no longer in use or needed, as well as allow them to pick up drawers and have them stack with other drawers in the inventory.

**Comment by MattiDragon** [comment]
Sneak-click on the drawer with an empty hand to remove upgrades

**Comment by bstrawsma** [comment]
Ahh thank you was killing myself over that not sure how I didn't try that

**Comment by Routhinator** [comment]
How do you remove a lock though?

**Comment by MattiDragon** [comment]
> How do you remove a lock though?
> 

Simply use it on the drawer again. The lock and everything else besides upgrades and limiters are toggles
