### ISSUE TITLE
[Feature]: Multiplier for Tier-Upgrades

### ISSUE THREAD

**Issue by floder91** [MattiDragon/ExtendedDrawers#48]
### Description of the feature

Since the drawers capacity is a bit too small for some Modpacks, it makes sense to add a multiplier for increasing the individual T-upgrades.

### How does it make the mod better?

Can be added some option in the config:
(config\extended_drawers\common.properties)

```
# Multiplier for the T1 upgrade, Default: 2*2
CapacityMultiplierT1 = 4
# Multiplier for the T2 upgrade, Default: 4*4
CapacityMultiplierT2 = 16
# Multiplier for the T3 upgrade, Default: 8*8
CapacityMultiplierT3 = 64
# Multiplier for the T4 upgrade, Default: 16*16
CapacityMultiplierT4 = 256
```
To get some higher Drawers capacity.

**Comment by MattiDragon** [comment]
Implemented in 1.3.9
