### ISSUE TITLE
[Bug]: 1.19.2 issue with another Mod, Items will disappear in the Drawers (Cincin: Better Nether)

### ISSUE THREAD

**Issue by suerion** [MattiDragon/ExtendedDrawers#51]
### Description of the issue

I had added 6 Stacks from Cincin ingots in the Drawers, but they disappear
Mod: https://www.curseforge.com/minecraft/mc-mods/betternether

### Reproduction steps

1. Use Item Pipe from Modern Dynamic
2. Add it in a Chest and Transport it with the Pipe to the Acces Point
3. No Items appear in the Drawers

### Mod version

Newest Update

### Operating System

Windows Server

### Minecraft version

1.19.2

### Other mods

[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
    [No Chat Reports (by Aizistral)](https://www.curseforge.com/minecraft/mc-mods/no-chat-reports)
    [MC Dungeons Armors (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcda)
    [You're in Grave Danger (by b1n_ry)](https://www.curseforge.com/minecraft/mc-mods/youre-in-grave-danger)
    [Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
    [MultiSleep (by Roaringmind22)](https://www.curseforge.com/minecraft/mc-mods/multisleep)
    [MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
    [Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
    [ServerCore (by Wesley8081)](https://www.curseforge.com/minecraft/mc-mods/servercore)
    [MC Dungeons Artifacts (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdar)
    [Macaw's Bridges - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go)
    [YUNG's Better Strongholds (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric)
    [FTB Teams (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric)
    [BCLib (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/bclib)
    [Your Options Shall Be Respected (YOSBR) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/yosbr)
    [🔨 Frame API (by Andante)](https://www.curseforge.com/minecraft/mc-mods/frame-api)
    [Elytra Slot (Fabric 1.16.1 - 1.19.2) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/elytra-slot-fabric)
    [Mixin Conflict Helper (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/mixin-conflict-helper)
    [YUNG's Better Desert Temples (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric)
    [Decorative Blocks (by stohun)](https://www.curseforge.com/minecraft/mc-mods/decorative-blocks)
    [JLine for Dedicated Server (by chirs241097)](https://www.curseforge.com/minecraft/mc-mods/jline-for-minecraft-dedicated-server)
    [YUNG's Better Ocean Monuments (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric)
    [Cull Less Leaves (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/cull-less-leaves)
    [Create Fabric (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/create-fabric)
    [Paladin's Furniture (by UnlikePaladin)](https://www.curseforge.com/minecraft/mc-mods/paladins-furniture)
    [Botany Trees (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-trees)
    [Exline's Furniture Mod (by exlinegames)](https://www.curseforge.com/minecraft/mc-mods/exlines-furniture)
    [Phosphor (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/phosphor)
    [Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
    [Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
    [Forge Config API Port [Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric)
    [Very Many Players (Fabric) (by ishlandmc)](https://www.curseforge.com/minecraft/mc-mods/vmp-fabric)
    [Macaw's Roofs (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs)
    [Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
    [Macaw's Fences - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-oh-the-biomes-youll-go)
    [Ledger (by potatoboy99999)](https://www.curseforge.com/minecraft/mc-mods/ledger)
    [Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
    [Vanish (by 123456687548)](https://www.curseforge.com/minecraft/mc-mods/vanish)
    [BetterEnd (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betterend)
    [Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
    [Macaw's Roofs - Oh The Biomes You'll Go (by Samlegamer_)](https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-oh-the-biomes-youll-go)
    [MixinTrace (by comp500)](https://www.curseforge.com/minecraft/mc-mods/mixintrace)
    [Repurposed Structures (Quilt/Fabric) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures-fabric)
    [Fabric Waystones (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/fabric-waystones)
    [Reese's Sodium Options (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/reeses-sodium-options)
    [FTB Backups 2 (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-backups-2)
    [Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
    [Oh The Biomes You'll Go Refabricated (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go-fabric)
    [YUNG's Better Witch Huts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric)
    [oωo (owo-lib) (by gliscowo)](https://www.curseforge.com/minecraft/mc-mods/owo-lib)
    [Carpet Extra (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet-extra)
    [Farmer's Delight [Fabric] (by NewHoryzon)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric)
    [Inv View (by potatoboy99999)](https://www.curseforge.com/minecraft/mc-mods/inv-view)
    [Sodium Extra (by FlashyReese)](https://www.curseforge.com/minecraft/mc-mods/sodium-extra)
    [Trinkets (Fabric) (by EmilyPloszaj)](https://www.curseforge.com/minecraft/mc-mods/trinkets)
    [Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
    [Farmer's Knives [Fabric] (by ianm1647)](https://www.curseforge.com/minecraft/mc-mods/farmers-knives)
    [DashLoader (by notequalalpha)](https://www.curseforge.com/minecraft/mc-mods/dashloader)
    [Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
    [Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
    [Grind Enchantments (by mschae23)](https://www.curseforge.com/minecraft/mc-mods/grind-enchantments)
    [Applied Energistics 2 (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2)
    [YUNG's Better Dungeons (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric)
    [Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
    [Patchouli (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/patchouli-fabric)
    [FTB Chunks (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric)
    [Player Roles (by gegybeans)](https://www.curseforge.com/minecraft/mc-mods/player-roles)
    [Macaw's Paintings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paintings)
    [Vertical Slabs Compat (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat)
    [BugJump (by Gugle)](https://www.curseforge.com/minecraft/mc-mods/bugjump)
    [Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
    [Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
    [Easy Magic [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/easy-magic)
    [TerraBlender (Fabric) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender-fabric)
    [Carpet TIS Addition (by Fallen_Breath)](https://www.curseforge.com/minecraft/mc-mods/carpet-tis-addition)
    [PolyLib (by Official_CreeperHost)](https://www.curseforge.com/minecraft/mc-mods/polylib)
    [Powah! (Rearchitected) (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected)
    [Modern Dynamics (by thetechnici4n)](https://www.curseforge.com/minecraft/mc-mods/modern-dynamics)
    [YUNG's Extras (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras-fabric)
    [spark (by Iucko)](https://www.curseforge.com/minecraft/mc-mods/spark)
    [LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
    [YUNG's API (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric)
    [Botania (Fabric/Quilt) (by williewillus)](https://www.curseforge.com/minecraft/mc-mods/botania-fabric)
    [YUNG's Bridges (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-bridges-fabric)
    [When Dungeons Arise - Fabric! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric)
    [BetterNether (by Quiqueck)](https://www.curseforge.com/minecraft/mc-mods/betternether)
    [Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
    [Botany Pots (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/botany-pots)
    [Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
    [Twigs (by ninnih_)](https://www.curseforge.com/minecraft/mc-mods/twigs)
    [lazy-language-loader (Fabric) (by chachylmao)](https://www.curseforge.com/minecraft/mc-mods/lazy-language-loader)
    [Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
    [Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
    [TimeOutOut (Fabric) (by potatoboy99999)](https://www.curseforge.com/minecraft/mc-mods/timeoutout-fabric)
    [Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
    [Adorn (by Juicebus)](https://www.curseforge.com/minecraft/mc-mods/adorn)
    [Archon (by safrodev)](https://www.curseforge.com/minecraft/mc-mods/archon)
    [Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
    [Ledger Databases (by Genau6502)](https://www.curseforge.com/minecraft/mc-mods/ledger-databases)
    [Dynamic FPS (by juliand665)](https://www.curseforge.com/minecraft/mc-mods/dynamic-fps)
    [Macaw's Bridges (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-bridges)
    [Carpet-Fixes (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/carpet-fixes)
    [Fabric Furnaces (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/fabric-furnaces)
    [YetAnotherConfigLib (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/yacl)
    [Indium (by comp500)](https://www.curseforge.com/minecraft/mc-mods/indium)
    [Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
    [Jade Addons (Fabric) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons-fabric)
    [Kibe Utilities (by D4rkness_King)](https://www.curseforge.com/minecraft/mc-mods/kibe)
    [MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
    [BetterF3 (by cominixo)](https://www.curseforge.com/minecraft/mc-mods/betterf3)
    [XL Packets Fabric (by tfarecnim)](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric)
    [Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
    [Extended Drawers (by MattiDragon)](https://www.curseforge.com/minecraft/mc-mods/extended-drawers)
    [Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
    [Traveler's Backpack [Fabric] (by Tiviacz1337)](https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric)
    [Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
    [Echoing Depths (by Draylar1)](https://www.curseforge.com/minecraft/mc-mods/echoing-depths)
    [MC Dungeons Weapons (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcdw)
    [Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
    [Macaw's Lights and Lamps (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-lights-and-lamps)
    [Furniture Expanded [FORGE/FABRIC] (by clumsycat)](https://www.curseforge.com/minecraft/mc-mods/furniture-expanded)
    [Icarus (by Cammie)](https://www.curseforge.com/minecraft/mc-mods/icarus)
    [FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
    [Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
    [Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
    [Cardinal Components (by UpcraftLP)](https://www.curseforge.com/minecraft/mc-mods/cardinal-components)
    [GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
    [YUNG's Better Mineshafts (Fabric) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric)
    [FTB Library (Fabric) (by FTB)](https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric)
    [Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)

### Server

Happens

### Client

Not tested

### Logs

NO Logissues

**Comment by MattiDragon** [comment]
Are you using a modpack? It'd make debugging easier

**Comment by MattiDragon** [comment]
Can't easily find the issue. Could you send a modpack link or instance for me to use? Have you also considered that items can get stored in modern dynamics extractors if they can't enter the target or source blocks? I'll close this in a while if you don't provide more exact steps with a smaller mod list or premade instance.

**Comment by MattiDragon** [comment]
I'll close this until you can provide more details
