### ISSUE TITLE
[Bug]: Modern Industrialization Item Pipes ignore locked status on drawers

### ISSUE THREAD

**Issue by therealbungus** [MattiDragon/ExtendedDrawers#53]
### Description of the issue

Hello there, I am running the All of Fabric 6 modpack 1.5.4 and added this mod (v1.3.9 for minecraft 1.19.2) due to a lack of storage options outside AE2. When connecting an item pipe from Modern Industralization (v1.6.5) to an access point in a locked drawer network, the item pipes insert things in every drawer in the network with an empty slot, including empty locked drawers. 

### Reproduction steps

1. Attach MI item pipe to an access point
2. Lock every drawer in the drawer network, including drawers with no items in them already.
3. Pipe items into the access point

### Mod version

1.3.9

### Operating System

Windows 10

### Minecraft version

1.19.2

### Other mods

Modern Industralization 1.6.5

### Server

Happens

### Client

Happens

### Logs

nothing related to this in logs whatsoever

**Comment by MattiDragon** [comment]
Could you check if hoppers do the same? I'm pretty sure the locked status of empty drawers is always ignored. I'll check myself later

**Comment by therealbungus** [comment]
Vanilla hoppers also do the same thing. The behavior in the original storage drawers mod was to respect locked status on empty drawers, it made it a lot easier to build a room of drawers that were locked and empty, then filling them in as needed.

**Comment by MattiDragon** [comment]
I need to rework some things to make it respect locked mode when empty because right now the same logic is used both for manual and automatic interactions. I'll try to get this fix today if possible

**Comment by MattiDragon** [comment]
Resolved in 1.3.10
