### ISSUE TITLE
[Bug]: If Upgraded Shulkers are installed at the same time, item can be copied and deleted.

### ISSUE THREAD

**Issue by QianFuv** [MattiDragon/ExtendedDrawers#56]
### Description of the issue

https://github.com/Qian-F/QFserver-Wonder/issues/2
https://github.com/MattiDragon/ExtendedDrawers/issues/17

Upgraded Shulkers: 
https://www.curseforge.com/minecraft/mc-mods/upgraded-shulkers

### Reproduction steps

https://github.com/Qian-F/QFserver-Wonder/assets/50223265/815dd0f7-7aca-46d6-a6fd-2927aad6820b

### Mod version

1.3.6

### Operating System

win11

### Minecraft version

1.18.2

### Other mods

fabric-api-0.76.0+1.18.2
upgradedshulkers-1.1.2.-1.18

### Server

Happens

### Client

Happens

### Logs

https://pastebin.com/y30xNdYC

**Comment by QianFuv** [comment]
https://github.com/MattiDragon/ExtendedDrawers/issues/17

**Comment by QianFuv** [comment]
@MattiDragon

**Comment by MattiDragon** [comment]
I'll get to debugging this today or tomorrow. I have no idea what could be wrong looking at the code

**Comment by QianFuv** [comment]
> I'll get to debugging this today or tomorrow. I have no idea what could be wrong looking at the code

Ok! Thank you for your dedication to this project!

**Comment by MattiDragon** [comment]
This issue is the fault of upgraded shulkers. It was fixed in their 1.1.3 update (not available on 1.18.2). Issue link: kyrptonaught/shulkerupgrades#18. I won't fix this as it's not my mod, nor a version that I support. You can contact them to get a fixed version out or do it yourself/get someone to do it. 

I suggest that you remove upgraded shulkers from your modpack unless you can get a fix as this will cause issues with many other mods.

**Comment by QianFuv** [comment]
> This issue is the fault of upgraded shulkers. It was fixed in their 1.1.3 update (not available on 1.18.2). Issue link: [kyrptonaught/shulkerupgrades#18](https://github.com/kyrptonaught/shulkerupgrades/issues/18). I won't fix this as it's not my mod, nor a version that I support. You can contact them to get a fixed version out or do it yourself/get someone to do it.
> 
> I suggest that you remove upgraded shulkers from your modpack unless you can get a fix as this will cause issues with many other mods.

Thanks for your reply! My server has planned to remove the Shulker box module!
