### ISSUE TITLE
[Bug]: Incompatibility with Applied Energistics 2

### ISSUE THREAD

**Issue by AkashiiKun** [MattiDragon/ExtendedDrawers#58]
### Description of the issue

Compacting drawers not working properly with Applied Energistics 2.

### Reproduction steps

1. Place a Drawer Access Point and connect it with the compacting drawer
2. connect an AE2 Storage Bus to the Drawer Access Point then to the AE2 Controller with an AE2 Crafting Terminal like in the picture.
![Step 2](https://github.com/MattiDragon/ExtendedDrawers/assets/44606942/ab5b3b3b-b742-4bf1-9ce1-f54020f5357e)
3. The terminal can't handle the drawer items properly.

### Mod version

1.4.0

### Operating System

Windows 11

### Minecraft version

1.19.2

### Other mods

Fabric API: 0.76.0+1.19.2
Applied Energistics 2: 1.4.0+mc.1.19.2

### Server

Not tested

### Client

Happens

### Logs

https://pastebin.com/zLNyrYBf

**Comment by MattiDragon** [comment]
My code was broken and AE happened to use it in such a way that it shows up. Will be fixed in 1.4.1
