### ISSUE TITLE
[Bug]: Missing Texture

### ISSUE THREAD

**Issue by bforbiggy** [MattiDragon/ExtendedDrawers#60]
### Description of the issue

Drawers are missing textures, both as a placed block and as an item.

### Reproduction steps

Simply place item down or view item from JEI. The texture will be the standard purple/black missing texture.

### Mod version

Extended Drawers 1.4.0 

### Operating System

Windows 11

### Minecraft version

1.19.2

### Other mods

05/22/2023  12:39 PM    <DIR>          .
05/22/2023  12:42 PM    <DIR>          ..
05/19/2023  10:02 PM           447,970 3dskinlayers-fabric-1.5.2-mc1.19.1.jar
05/19/2023  10:27 PM         4,181,260 AdditionalAdditions-5.1.0.jar
05/20/2023  02:39 PM           192,525 AdvancementPlaques-1.19.2-fabric-1.4.6.jar
05/19/2023  11:55 PM        10,198,308 ad_astra-fabric-1.19.2-1.12.6.jar
05/19/2023  09:33 PM        77,137,995 AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
05/19/2023  11:38 PM         1,543,486 another_furniture-fabric-2.1.2-1.19.2.jar
05/19/2023  09:17 PM         1,040,951 appleskin-fabric-mc1.19-2.4.1.jar
05/19/2023  09:36 PM           563,704 architectury-6.5.82-fabric.jar
05/20/2023  02:53 PM           599,880 artifacts-7.1.1+fabric.jar
05/21/2023  06:52 PM         1,268,682 automobility-0.4.11.19.2-fabric.jar
05/19/2023  09:43 PM         1,892,520 bclib-2.1.6.jar
05/19/2023  09:43 PM        80,545,681 better-end-2.1.5.jar
05/19/2023  09:43 PM        21,952,267 better-nether-7.1.3.jar
05/19/2023  09:29 PM            72,871 BetterAdvancements-Fabric-1.19.2-0.2.2.147.jar
05/19/2023  11:47 PM           189,174 BetterAnimationsCollection-v4.0.5-1.19.2-Fabric.jar
05/19/2023  09:52 PM           758,708 bettercombat-fabric-1.7.1+1.19.jar
05/19/2023  10:00 PM            55,420 BetterThirdPerson-Fabric-1.19-1.9.0.jar
05/19/2023  09:55 PM         1,625,827 bettervillage-fabric-1.19.2-3.1.0.jar
05/19/2023  09:40 PM         5,560,366 bewitchment-1.19-7.jar
05/19/2023  11:40 PM           167,217 blur-2.6.0.jar
05/19/2023  09:36 PM           294,279 Bookshelf-Fabric-1.19.2-16.2.18.jar
05/19/2023  11:27 PM           136,409 botarium-fabric-1.19.2-1.8.2.jar
05/19/2023  10:13 PM           603,432 BountifulFabric-4.0.0.jar
05/20/2023  02:27 PM            19,589 bwncr-fabric-1.19.2-3.14.1.jar
05/19/2023  10:25 PM           122,465 capybara-1.19-2.0.1.jar
05/19/2023  11:28 PM           382,579 carryon-fabric-1.19.2-2.0.5.11.jar
05/19/2023  11:49 PM         6,708,923 Chimes-1.1.4-1.19.2-Fabric.jar
05/21/2023  12:43 AM         2,014,737 chisels-and-bits-fabric-1.3.135.jar
05/19/2023  09:17 PM         1,141,796 cloth-config-8.2.88-fabric.jar
05/19/2023  09:18 PM            20,577 Clumps-fabric-1.19.4-10.0.0.2.jar
05/19/2023  09:54 PM           578,981 collective-1.19.2-6.53.jar
05/20/2023  03:05 PM           621,824 ColorfulAzaleas-fabric-1.19.2-2.3.1.jar
05/19/2023  11:45 PM           173,599 combatroll-fabric-1.1.5+1.19.jar
05/20/2023  02:39 PM           668,703 comforts-fabric-6.0.4+1.19.2.jar
05/19/2023  09:17 PM           120,302 Controlling-fabric-1.19.2-10.0+7.jar
05/19/2023  10:46 PM           512,931 CorgiLib-fabric-1.19.2-1.0.0.33.jar
05/19/2023  10:27 PM           356,678 Couplings-1.9.1+1.19.jar
05/19/2023  10:09 PM            98,889 crawl-0.11.1.jar
05/19/2023  09:12 PM        18,066,675 create-fabric-0.5.0.i-1017+1.19.2.jar
05/19/2023  09:30 PM           932,706 createaddition-fabric+1.19.2-20230508b.jar
05/19/2023  09:36 PM           973,793 CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
05/19/2023  10:10 PM           596,998 CreaturesFromTheSnow-4.1.0+1.19.2.jar
05/19/2023  09:33 PM         1,099,687 creeperoverhaul-2.0.9-fabric.jar
05/19/2023  09:34 PM         1,040,817 crittersandcompanions-fabric-1.19.2-1.0.3.jar
05/19/2023  09:59 PM           177,736 DarkUtilities-Fabric-1.19.2-13.1.7.jar
05/20/2023  02:26 PM           506,697 Decorative+Blocks-fabric-1.19.2-3.0.0.jar
05/19/2023  09:58 PM        19,367,092 deeperdarker-fabric-1.1.6-fabric.jar
05/19/2023  10:34 PM         1,223,262 drinkbeer-3.2.2-1.19.2.jar
05/20/2023  02:42 PM           140,725 EasyAnvils-v4.0.11-1.19.2-Fabric.jar
05/19/2023  11:46 PM           991,062 eating-animation-1.9.1.jar
05/19/2023  09:33 PM         2,796,654 ecologics-fabric-1.19.2-2.1.11.jar
05/19/2023  10:13 PM        20,351,140 eden-ring-0.6.4.jar
05/19/2023  10:19 PM           827,637 effective-1.4.jar
05/19/2023  10:11 PM            50,903 elytraslot-fabric-6.1.1+1.19.2.jar
05/19/2023  09:18 PM            58,073 EnchantmentDescriptions-Fabric-1.19.2-13.0.14.jar
05/19/2023  10:47 PM        51,762,259 enderscape-0.4.1-1.19.2.jar
05/20/2023  02:25 PM            57,471 entityculling-fabric-1.6.1-mc1.19.2.jar
05/19/2023  09:15 PM            19,211 Essential-fabric_1-19.jar
05/19/2023  09:11 PM         1,882,121 fabric-api-0.76.0+1.19.2.jar
05/19/2023  10:14 PM         6,578,017 fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
05/19/2023  10:12 PM           149,328 fallingleaves-1.13.0+1.19.2.jar
05/19/2023  09:42 PM         2,705,516 farmers-delight-fabric-1.19.X-1.3.9.jar
05/20/2023  02:31 PM           567,412 Fastload+1.18.2-1.20-3.4.0.jar
05/20/2023  02:26 PM           439,991 ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar
05/19/2023  10:10 PM         2,491,306 friendsandfoes-fabric-mc1.19.2-1.8.2.jar
05/19/2023  10:20 PM         1,918,025 frozenup-2.1.0-fabric.jar
05/19/2023  10:07 PM         5,956,527 Galosphere-1.19.2-1.2.2-Fabric.jar
05/19/2023  09:35 PM         3,619,195 geckolib-fabric-1.19-3.1.40.jar
05/20/2023  02:38 PM           321,607 go-fish-1.6.0-1.19.1.jar
05/19/2023  10:12 PM           619,176 goodall-1.2.0-fabric.jar
05/19/2023  10:07 PM           243,361 guard-villagers-fabric-1.19.2-1.1.2.jar
05/20/2023  04:14 PM         2,494,952 handcrafted-fabric-1.19.2-2.0.6.jar
05/19/2023  10:37 PM         1,181,050 hookshot-26.0.jar
05/19/2023  11:50 PM           188,847 icarus-1.14.jar
05/19/2023  11:54 PM            79,522 Iceberg-1.19.1-fabric-1.0.46.jar
05/20/2023  03:16 PM         4,834,285 immersive_paintings-0.6.0+1.19.2-fabric.jar
05/19/2023  10:29 PM           266,265 impaled-1.1.4.jar
05/20/2023  02:37 PM         4,357,270 Incendium_1.19.3_v5.1.6.jar
05/19/2023  10:42 PM           118,642 indium-1.0.9+mc1.19.2.jar
05/22/2023  11:36 AM           215,383 invhud.fabric.1.19-3.4.7.jar
05/19/2023  10:08 PM         2,806,426 iris-mc1.19.2-1.6.2.jar
05/22/2023  12:14 PM           354,663 ironchests-3.1.1-fabric.jar
05/19/2023  09:58 PM            59,012 ItemPhysic_FABRIC_v1.6.6_mc1.19.2.jar
05/19/2023  09:29 PM           436,662 Jade-1.19.1-fabric-8.7.3.jar
05/19/2023  10:32 PM            66,098 jamlib-0.6.0+1.19.jar
05/19/2023  09:16 PM         1,117,763 jei-1.19.2-fabric-11.6.0.1015.jar
05/19/2023  09:29 PM           269,219 JustEnoughResources-Fabric-1.19.2-1.1.0.179.jar
05/19/2023  10:14 PM           408,639 Kambrik-4.0-1.19.2.jar
05/19/2023  11:44 PM            55,553 LegendaryTooltips-1.19.2-fabric-1.3.3.jar
05/19/2023  09:55 PM           171,232 libraryferret-fabric-1.19.2-4.0.0.jar
05/19/2023  09:57 PM           639,001 lithium-fabric-mc1.19.2-0.11.1.jar
05/19/2023  11:37 PM           568,157 mavapi-1.0.1-mc1.19.2.jar
05/19/2023  11:36 PM           728,709 mavm-1.2.0-mc1.19.2.jar
05/19/2023  10:28 PM           701,437 mcw-bridges-2.0.7-mc1.19.2fabric.jar
05/20/2023  03:22 PM         1,200,787 mcw-doors-1.0.9fabric-mc1.19.2.jar
05/19/2023  10:28 PM           378,324 mcw-fences-1.0.7-mc1.19.2fabric.jar
05/19/2023  10:28 PM           329,988 mcw-lights-1.0.5-mc1.19.2fabric.jar
05/19/2023  10:28 PM           949,284 mcw-windows-2.1.2-mc1.19.2fabric.jar
05/19/2023  10:17 PM           692,192 modmenu-4.2.0-beta.2.jar
05/19/2023  09:32 PM           835,958 moonlight-1.19.2-2.2.33-fabric.jar
05/19/2023  10:26 PM           167,559 moremobvariants-1.0.1-1.19.2.jar
05/20/2023  03:59 PM           692,187 mostructures-1.4.3+1.19.2.jar
05/19/2023  09:16 PM            77,282 MouseTweaks-fabric-mc1.19-2.22.jar
05/20/2023  07:48 PM         1,061,531 mousewheelie-1.11.0+mc1.19.2.jar
05/19/2023  10:42 PM           464,351 moyai-1.19.2-2.0.0-fabric.jar
05/19/2023  10:14 PM           410,977 mru-0.1.5+1.19.2.jar
05/19/2023  10:20 PM           229,915 mysticaloaktree-1.19.2-1.8-fabric.jar
05/19/2023  10:20 PM         4,360,430 mythic-mounts-1.19.2-7.2.jar
05/19/2023  10:13 PM           790,756 NethersDelight-1.0.1.jar
05/19/2023  09:38 PM           409,863 notenoughanimations-fabric-1.6.2-mc1.19.2.jar
05/19/2023  10:48 PM           364,396 Nullscape_1.19.3_v1.2.1.jar
05/19/2023  10:43 PM        37,915,825 Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.1.jar
05/19/2023  10:33 PM           780,597 owo-lib-0.9.3+1.19.jar
05/20/2023  03:48 PM         5,387,251 paladin-furniture-mod-1.1.1-fabric-mc1.19.jar
05/19/2023  10:12 PM        44,611,383 paradise-lost-2.1.0-beta+1.19.2.jar
05/19/2023  10:01 PM           851,784 Patchouli-1.19.2-77-FABRIC.jar
05/19/2023  10:01 PM           465,441 Pehkui-3.7.3+1.14.4-1.20.jar
05/19/2023  10:24 PM            88,018 phosphor-fabric-mc1.19.x-0.8.1.jar
05/20/2023  02:30 PM            91,402 PickUpNotifier-v4.2.4-1.19.2-Fabric.jar
05/19/2023  09:59 PM            10,991 PigPen-Fabric-1.19.2-11.1.2.jar
05/19/2023  09:52 PM           180,871 player-animation-lib-fabric-1.0.2.jar
05/19/2023  10:06 PM           629,377 polymorph-fabric-0.46.1+1.19.2.jar
05/19/2023  11:44 PM         7,221,534 PresenceFootsteps-1.6.4.jar
05/19/2023  11:55 PM            57,198 Prism-1.19.2-fabric-1.0.3.jar
05/19/2023  11:40 PM           437,098 Public+GUI+Announcement-fabric-1.19.2-4.3.3.jar
05/19/2023  10:02 PM           525,817 PuzzlesLib-v4.4.0-1.19.2-Fabric.jar
05/20/2023  03:14 PM           287,347 ratsmischief-1.4.0.jar
05/19/2023  09:37 PM           128,481 resourcefulconfig-fabric-1.19.2-1.0.20.jar
05/19/2023  11:57 PM           229,931 resourcefullib-fabric-1.19.2-1.1.24.jar
05/19/2023  09:43 PM         1,386,673 rottencreatures-fabric-1.19.2-1.0.1.jar
05/19/2023  09:59 PM            49,313 Runelic-Fabric-1.19.2-14.1.4.jar
05/19/2023  10:21 PM           258,186 runes-fabric-0.9.8+1.19.jar
05/19/2023  11:48 PM        32,098,186 simplyswords-fabric-1.46.1-1.19.2.jar
05/20/2023  02:53 PM           246,319 SkyVillages-1.0.2.1-1.19.x-fabric.jar
05/19/2023  10:35 PM         1,372,575 sodium-fabric-mc1.19.2-0.4.4+build.18.jar
05/19/2023  09:35 PM         2,941,997 spark-1.10.37-fabric.jar
05/19/2023  10:32 PM         1,061,070 spell_engine-fabric-0.9.16+1.19.jar
05/19/2023  10:32 PM           159,566 spell_power-fabric-0.9.11+1.19.jar
05/19/2023  10:27 PM           120,179 spiderstpo-fabric-1.19.2-2.0.3.jar
05/20/2023  02:49 PM         2,797,531 Steam_Rails-1.2.6+fabric-mc1.19.2.jar
05/20/2023  03:55 PM           712,210 steves_vanilla-1.19.2+2.0.1.jar
05/19/2023  10:13 PM         1,102,933 Strawgolem-fabric-1.19.2-2.0.0-beta.5.jar
05/19/2023  09:56 PM         1,243,852 Structory_1.19.3_v1.3.1a.jar
05/20/2023  02:34 PM        14,350,518 supplementaries-1.19.2-2.3.11-fabric.jar
05/19/2023  10:43 PM           307,148 TerraBlender-fabric-1.19.2-2.0.1.136.jar
05/19/2023  10:11 PM        10,965,613 the_bumblezone_fabric-6.7.19+1.19.2.jar
05/20/2023  03:53 PM        13,641,529 The_Graveyard_2.3.1_(FABRIC)_for_1.19.2.jar
05/19/2023  10:03 PM           426,809 things-0.3.0+1.19.jar
05/20/2023  03:08 PM           209,669 thonkutil-2.15.4+1.19.jar
05/19/2023  09:34 PM           117,040 Tips-Fabric-1.19.2-8.0.27.jar
05/21/2023  11:15 AM         1,524,403 toms_storage_fabric-1.19-1.5.6.jar
05/19/2023  11:41 PM         2,822,845 Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar
05/19/2023  09:51 PM           214,813 TravelersTitles-1.19.2-Fabric-3.1.0.jar
05/19/2023  09:54 PM           104,331 treeharvester-1.19.2-8.0.jar
05/19/2023  09:38 PM           238,556 trinkets-3.4.2.jar
05/20/2023  03:55 PM           272,023 untitledduckmod-0.6.1-1.19.2-fabric.jar
05/20/2023  02:32 PM            67,249 visuality-0.5.6.jar
05/20/2023  02:22 PM            79,961 VisualWorkbench-v4.2.4-1.19.2-Fabric.jar
05/19/2023  09:51 PM           146,541 weaponmaster-multi-fabric-1.19-3.0.2.jar
05/19/2023  10:21 PM         2,101,146 wizards-fabric-0.9.14+1.19.jar
05/20/2023  02:24 PM           711,951 wondrouswilds-1.19.2-1.1.6.jar
05/19/2023  09:49 PM           401,874 wraith-waystones-3.0.7+mc1.19.2.jar
05/19/2023  10:43 PM         2,004,587 WWOO-FABRIC-3.1.9.1.jar
05/19/2023  09:29 PM           839,348 XaerosWorldMap_1.30.2_Fabric_1.19.1.jar
05/19/2023  09:29 PM         1,374,030 Xaeros_Minimap_23.4.3_Fabric_1.19.1.jar
05/21/2023  11:17 AM           202,452 YetAnotherConfigLib-2.2.0-for-1.19.2.jar
05/20/2023  02:33 PM           336,303 youre-in-grave-danger-1.4.9.jar
05/19/2023  09:49 PM         1,220,468 YungsApi-1.19.2-Fabric-3.8.9.jar
05/19/2023  09:50 PM         1,132,583 YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar
05/19/2023  09:50 PM         1,162,780 YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
05/19/2023  09:49 PM           278,685 YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
05/19/2023  09:53 PM           962,328 YungsBetterNetherFortresses-1.19.2-Fabric-1.0.5.jar
05/19/2023  09:50 PM         1,414,502 YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0.jar
05/19/2023  09:50 PM           248,312 YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
05/19/2023  09:50 PM           386,484 YungsBridges-1.19.2-Fabric-3.1.0.jar
05/19/2023  09:51 PM           428,068 YungsExtras-1.19.2-Fabric-3.1.0.jar
05/20/2023  02:53 PM           461,672 [Universal]Immersive+Structures-2.0.7a.jar
05/20/2023  07:01 PM    <DIR>          _bclib_deactivated

### Server

Not tested

### Client

Happens

### Logs

N/A

**Comment by MattiDragon** [comment]
You need thonkutil 2.15.5. It had a bug in older versions

**Comment by totrider** [comment]
This bug is still a problem in 1.19.2, and ThonkUtil 2.15.5 is not available for 1.19.2, only 1.19

**Comment by MattiDragon** [comment]
> This bug is still a problem in 1.19.2, and ThonkUtil 2.15.5 is not available for 1.19.2, only 1.19

1.19 and 1.19.2 should be compatible. If it doesn't work then you have to remove thonkutil. It is their fault and they are responsible for porting the fix
