### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by RavenRose0** [MattiDragon/ExtendedDrawers#61]
### Description of the issue

i used drawer access point to put my emerald and insted of sorting it . it vanished 

### Reproduction steps

i used double right click to insert
and it vanshed

### Mod version

aqm2

### Operating System

windows10

### Other mods

Extended drawer 

### Server

Not tested

### Client

Not tested

### Logs

a

**Comment by MattiDragon** [comment]
You're missing important information. Please fill in minecraft version, mod version and other mods properly. It would also help if you figure out a way to reliably reproduce this issue and reduce the amount of mods needed.

Please also check that you don't have a drawer you don't know about on the network

**Comment by MattiDragon** [comment]
Closing this as incomplete, reopen once you can provide the necessary information and reproduction steps
