### ISSUE TITLE
[Feature]: Compatibility to PaperMC

### ISSUE THREAD

**Issue by sr972** [MattiDragon/ExtendedDrawers#62]
### Description of the feature

Compatibility to PaperMC servers

### How does it make the mod better?

Right now this (really good) mod is available on fabrics/quilt only.
Is there a chance, this mod would be available as an PaperMC compatible mod too?
Is there a way to possible help by this feature request (my Java coding skills are not good)?

**Comment by MattiDragon** [comment]
This mod will never be on paper. This mod currently requires being installed on the client. It would be possible to recreate, but I won't do it. I'm not interested in working with the limiting plugin apis. 

You should consider using a fabric server instead, many of the most important plugin exist as mods, and you can often get better performance on fabric. Even then this mod is required on the client. The upcoming polyfactory mod by patbox will include a drawer feature. It's a fully server side fabric tech mod. 

I'm happy to help you find alternatives for your plugins if you want to change to a fabric server if you join our discord.
