### ISSUE TITLE
[Bug]: Drawer Access Point causes item counts to not update.

### ISSUE THREAD

**Issue by wkpatrick** [MattiDragon/ExtendedDrawers#68]
### Description of the issue

Here is my setup

Chest -> Hopper -> Drawer Access Point connected to a group of drawers.

I put some items into the chest and saw that the item count on the drawers was not updating. I then took a few items out of the drawer manually, and right click inserted them into the access point. The item count continued to stay the same. These items were not at the stack limit, nor were their drawers set to void them if they went over the limit.Breaking the drawer access point and replacing it would make the item count increase when items were inserted.

The drawers and access point are all in the same chunk, but the funnel and half of the double chest that feed it are 1 block into the next chunk.

This is part is unreliable: I think that emptying the drawer by shift clicking made it dispense the correct amount of items. 

This occurred on a dedicated server. 

### Reproduction steps

n/a. Not able to reproduce this myself yet. I will continue testing to see if I can.

### Mod version

ExtendedDrawers-1.4.1+mc.1.19.4

### Operating System

Debian

### Minecraft version

1.19.4

### Other mods

Client Mods:
  [✔] advancementinfo-1.19.4-fabric0.76.0-1.3.1
  [✔] antighost-1.19.3-fabric0.68.1-1.1.5
  [✔] badpackets-fabric-0.4.1
  [✔] betterbeds-1.3.0-1.19.3
  [✔] BetterF3-6.0.2-Fabric-1.19.4
  [✔] bettermounthud-1.2.1
  [✔] borderless-mining-1.1.7+1.19.4
  [✔] capes-1.5.2+1.19.3-fabric
  [✔] cardinal-components-api-5.1.0
  [✔] CITResewn-1.1.3+1.19.4
  [✔] cloth-config-10.0.96-fabric
  [✔] continuity-3.0.0-beta.2+1.19.3
  [✔] Debugify-1.19.4+2.2
  [✔] dynamic-fps-2.2.0
  [✔] e4mc-3.2.0+1.19.4-fabric
  [✔] emi-1.0.2+1.19.4+fabric
  [✔] entity_model_features_fabric_1.19.4-0.2.9
  [✔] entity_texture_features_fabric_1.19.4-4.4.4
  [✔] entityculling-fabric-1.6.2-mc1.19.4
  [✔] expandedstorage-9.0.4+1.19.4-fabric
  [✔] ExtendedDrawers-1.4.1+mc.1.19.4
  [✔] fabric-api-0.83.0+1.19.4
  [✔] fabric-language-kotlin-1.9.4+kotlin.1.8.21
  [✔] fabricskyboxes-0.7.1+mc1.19.4
  [✔] fabrishot-1.9.2
  [✔] farsight-fabric-1.19-3.4
  [✔] fastquit-2.1.0+1.19.3
  [✔] ferritecore-5.2.0-fabric
  [✔] ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric
  [✔] fsb-interop-1.3.1+mc1.19.4-build.33
  [✔] ImmediatelyFast-1.1.12+1.19.4
  [✔] indium-1.0.15+mc1.19.4
  [✔] InventoryProfilesNext-fabric-1.19.4-1.10.2
  [✔] iris-mc1.19.4-1.6.3
  [✔] jamlib-0.6.0+1.19.4
  [✔] lambdynamiclights-2.3.0+1.19.4
  [✔] language-reload-1.5.5+1.19.4
  [✔] libIPN-fabric-1.19.4-3.0.2-SNAPSHOT
  [✔] lithium-fabric-mc1.19.4-0.11.1
  [✔] main-menu-credits-1.1.2
  [✔] memoryleakfix-fabric-1.17+-1.0.0
  [✔] midnightcontrols-1.8.1+1.19.4
  [✔] mine-treasure-1.2.8
  [✔] mixintrace-1.1.1+1.17
  [✔] modelfix-1.10-fabric
  [✔] modmenu-6.2.2
  [✔] morechathistory-1.19.1-1.1.1
  [✔] moreculling-1.19.4-0.17.0
  [✔] NoChatReports-FABRIC-1.19.4-v2.1.4
  [✔] nofade-1.18-2.0.1
  [✔] open-parties-and-claims-fabric-1.19.4-0.17.5
  [✔] optigui-2.1.0-beta.3
  [✔] owo-lib-0.10.6+1.19.4
  [✔] puzzle-1.5.0+1.19.4
  [✔] reeses_sodium_options-1.5.0+mc1.19.4-build.72
  [✔] right-click-harvest-3.2.2+1.19.x-1.20-fabric
  [✔] sodium-extra-0.4.18+mc1.19.4-build.100
  [✔] sodium-fabric-mc1.19.4-0.4.10+build.24
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] travelers-backpack-1.19.4-8.4.4
  [✔] wraith-waystones-3.1.1+mc1.19.4
  [✔] wthit-fabric-7.3.1
  [✔] Xaeros_Minimap_23.4.4_Fabric_1.19.4
  [✔] XaerosWorldMap_1.30.3_Fabric_1.19.4
  [✔] yet-another-config-lib-fabric-2.5.1+1.19.4
  [✔] yosbr-0.1.1
  [✔] youre-in-grave-danger-1.6.0
  [✔] YungsApi-1.19.4-Fabric-3.10.1
  [✔] YungsBetterDesertTemples-1.19.4-Fabric-2.4.0
  [✔] YungsBetterDungeons-1.19.4-Fabric-3.4.0
  [✔] YungsBetterMineshafts-1.19.4-Fabric-3.4.0
  [✔] YungsBetterNetherFortresses-1.19.4-Fabric-1.2.0
  [✔] YungsBetterOceanMonuments-1.19.4-Fabric-2.3.0
  [✔] YungsBetterStrongholds-1.19.4-Fabric-3.4.0
  [✔] YungsBetterWitchHuts-1.19.4-Fabric-2.3.0
  [✔] YungsBridges-1.19.4-Fabric-3.3.0
  [✔] YungsExtras-1.19.4-Fabric-3.3.0
  [✔] Zoomify-2.9.4
  
Server Mods:
badpackets-fabric-0.4.1.jar
BetterF3-6.0.2-Fabric-1.19.4.jar
cardinal-components-api-5.1.0.jar
cloth-config-10.0.96-fabric.jar
emi-1.0.2+1.19.4+fabric.jar
expandedstorage-9.0.4+1.19.4-fabric.jar
ExtendedDrawers-1.4.1+mc.1.19.4.jar
fabric-api-0.83.0+1.19.4.jar
fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
ForgeConfigAPIPort-v6.0.2-1.19.4-Fabric.jar
InventoryProfilesNext-fabric-1.19.4-1.10.2.jar
jamlib-0.6.0+1.19.4.jar
libIPN-fabric-1.19.4-3.0.2-SNAPSHOT.jar
mine-treasure-1.2.8.jar
open-parties-and-claims-fabric-1.19.4-0.17.5.jar
owo-lib-0.10.6+1.19.4.jar
right-click-harvest-3.2.2+1.19.x-1.20-fabric.jar
travelers-backpack-1.19.4-8.4.4.jar
wraith-waystones-3.1.1+mc1.19.4.jar
wthit-fabric-7.3.1.jar
Xaeros_Minimap_23.4.4_Fabric_1.19.4.jar
XaerosWorldMap_1.30.3_Fabric_1.19.4.jar
youre-in-grave-danger-1.6.0.jar
YungsApi-1.19.4-Fabric-3.10.1.jar
YungsBetterDesertTemples-1.19.4-Fabric-2.4.0.jar
YungsBetterDungeons-1.19.4-Fabric-3.4.0.jar
YungsBetterMineshafts-1.19.4-Fabric-3.4.0.jar
YungsBetterNetherFortresses-1.19.4-Fabric-1.2.0.jar
YungsBetterOceanMonuments-1.19.4-Fabric-2.3.0.jar
YungsBetterStrongholds-1.19.4-Fabric-3.4.0.jar
YungsBetterWitchHuts-1.19.4-Fabric-2.3.0.jar
YungsBridges-1.19.4-Fabric-3.3.0.jar
YungsExtras-1.19.4-Fabric-3.3.0.jar

### Server

Happens

### Client

Not tested

### Logs

https://pastebin.com/UMPSTnht

### Extra Context

Screenshot of the drawer setup is located at https://github-production-user-asset-6210df.s3.amazonaws.com/23044139/245327354-0a876331-f038-4d1e-bad4-db93322ceeb9.png

**Comment by MattiDragon** [comment]
Try using the `/graphlib debugrender start` command. It should enable a debug overlay of drawer connections.. If you have somehow ended up with multiple networks then you can fix it with another `/graphlib` command (don't remember it)

**Comment by JustusFluegel** [comment]
Just want to add that I had the same issue in one of my worlds on a dedi server as well

**Comment by MattiDragon** [comment]
Closing this until I can get proper reproduction steps
