### ISSUE TITLE
[Crash]: Server Crash: Ticking block entity

### ISSUE THREAD

**Issue by rxay579** [MattiDragon/ExtendedDrawers#70]
### Description of the issue

MC v1.19.4, Fabric API v0.83.0, Tom's Simple Storage Mod v1.5.8, Extended Drawers v1.4.1

I mis-clicked and placed an Extended Drawers Compacting Drawer next to a Mythic Metals single chest that was part of an existing Tom's storage network.

Also reported here: https://github.com/tom5454/Toms-Storage/issues/257

[2023-06-28-1.log](https://github.com/MattiDragon/ExtendedDrawers/files/11892924/2023-06-28-1.log)
[crash-2023-06-28_03.02.45-server.txt](https://github.com/MattiDragon/ExtendedDrawers/files/11892876/crash-2023-06-28_03.02.45-server.txt)

[2023-06-28-2.log](https://github.com/MattiDragon/ExtendedDrawers/files/11892927/2023-06-28-2.log)
[crash-2023-06-28_03.10.51-server.txt](https://github.com/MattiDragon/ExtendedDrawers/files/11892878/crash-2023-06-28_03.10.51-server.txt)

### Reproduction steps

1. Place Compacting Drawer into Tom's Simple Storage network.
2. Server crashes and disconnects the client.

### Mod version

v1.4.1

### Operating System

Windows 10

### Minecraft version

1.19.4

### Other mods

Tom's Simple Storage v1.58.
Full list appears in crashlog.

### Server

Happens

### Client

Not tested

### Logs

Uploaded in description

### Crash Report

Uploaded in description

### Extra Context

I had a chunk loader in the storage chunk.

I added "Neruina - Ticking Entity Fixer" to the server and restarted it again.
The server started, a log entry mentioned the ticking block but prevented the crash.
I logged back in, broke and picked up the inventory connector, broke and moved the compacting drawer, then replaced the inventory connector and checked the terminal; the network appeared to be intact.

I've since restarted the server again without Neruina enabled and things appear to be normal again.
I have not tried placing any regular (single, double, quad) extended drawers directly to the Tom's Simple Storage network.

I haven't had stability/crash issues with the extended drawers when connecting a tom's filtered connector to the extended drawers access point.

**Comment by MattiDragon** [comment]
Can't reproduce with just extended drawers and toms simple storage or if I add mythic metals decorations from the logs. Try finding a minimal test case and I can try again.

**Comment by rxay579** [comment]
Minimum viable test to reproduce includes:
MC v1.19.4, Fabric API v0.83.0, Tom's Simple Storage Mod v1.5.8, Extended Drawers v1.4.1, Mythic Metals Decorations v0.5.3, and dependencies.  Full list in logs.
Tested in new single player superflat world in Creative.

World bricked after placing Compacting Drawer on top of Bronze Chest.
[2023-06-28-7.log](https://github.com/MattiDragon/ExtendedDrawers/files/11898979/2023-06-28-7.log)

Added Neruina to stop the "ticking entity" for easier testing.
[latest.log](https://github.com/MattiDragon/ExtendedDrawers/files/11898980/latest.log)

Does not occur when placed next to or under the bronze chest.
Same issue occurs with any drawer (single, double, quad, compacting).
The Tom's Simple Storage terminal is not required, only the Inventory Connector.

Bricked world:
![2023-06-28_13 38 50 - Crashing](https://github.com/MattiDragon/ExtendedDrawers/assets/67221030/d226016a-48a9-4a13-af3b-ded89aa948e9)

Working world:
![2023-06-28_13 38 58 - Not Crashing](https://github.com/MattiDragon/ExtendedDrawers/assets/67221030/949c44ec-d6db-4919-a22a-f7c3e21b515c)

**Comment by tom5454** [comment]
It's Mythic Metals Decorations custom inventory handler breaking here:
https://github.com/Noaaan/MythicMetalsDecorations/blob/1.20/src/main/java/nourl/mythicmetalsdecorations/MythicMetalsDecorations.java#L73
The `MythicChestBlock.getInventory` returns null
