### ISSUE TITLE
[Bug]: Access points stop seeing drawers 

### ISSUE THREAD

**Issue by L3G1T1SM3** [MattiDragon/ExtendedDrawers#71]
### Description of the issue

I have two drawer walls(not connected to each other) and their access points have stopped allowing items to be right clicked into them to be added to the wall. Putting a crafting and storage terminal(From toms simple storage) on them had in the past allowed for a rudimentary ae2esq me system which would correctly show all the items from the wall. Now suddenly they do not work doing 3 things. 

1. Right clicking to dump items to said wall
2. See any of the drawers attached when using either the crafting terminal or the storage terminal
3. Occasionally will allow for seeing certain drawers but only around 3-4 of the drawers out of 40 or so

Also the access point in the second room when paired with a terminal will see a dual drawer regardless of if it is connected to it in any way. See attached images. 
*I am aware they need to be surrounded by drawers to see other drawers. This is an issue on top of not working as intended with APs*

Even more oddities. Rebuilding a small access point and drawer system above my storage does make a AP and Drawer system that does seem to work. And other Drawer Wall and APs do work elsewhere on the server. (I can post logs or whatever too if needed.) 

Attempts to fix:
Running /graphlib debugrender start kicks me from server even though I am opped
replacing configs with provided ones from STATECH Industry 
Breaking and Replacing access points with new ones 
Moving problematic drawers to a new area and making a small wall with an ap and crafting terminal>**This works fine** 

Modpack:STATECH Industry version 1.0.4. 
Tom's Simple Storage version is 1.5.7
I did upgrade to 1.0.0 to 1.0.4 and this occurred a good while after upgrading. 

### Reproduction steps

I would attempt to replicate this issues but given the walls work elsewhere on the server I have no point of reference as to what caused this or when other than it started yesterday suddenly. Perhaps after a crash or restart though. If needed i can post crash logs.

### Mod version

1.4.1

### Operating System

Windows 10

### Minecraft version

1.19.2

### Other mods

https://github.com/TheStaticVoid/StaTech-Industry/tree/main/mods

### Server

Happens

### Client

Not tested

### Logs

https://gist.github.com/L3G1T1SM3/4e9edc5e3a1923677f6082275e4556e0

### Extra Context

![2023-07-04_17 22 14](https://github.com/MattiDragon/ExtendedDrawers/assets/138430032/5a66577c-4a08-480a-be6a-a0322131957b)
![2023-07-04_17 22 16](https://github.com/MattiDragon/ExtendedDrawers/assets/138430032/7893a9ab-71a6-46c2-b9b3-4c2507d28d0f)

**Comment by MattiDragon** [comment]
Closing for now. If you have reliable reproduction steps, please send them
