### ISSUE TITLE
[Crash]: 

### ISSUE THREAD

**Issue by San194** [MattiDragon/ExtendedDrawers#73]
### Description of the issue

I placed the quad-drawer storage barrels. Everything was fine until I created the lock to lock the drawers.

I sneaked and right clicked the barrel to lock it (after reading online that's how it is done), and that is when the problems started. This is on a server by the way, although the crash seems to be purely on the client side.

The game crashes every single time I log into the world, and the server does not crash. It seems to be a loading-texture problem.

### Reproduction steps

1. Place quad-storage barrel.
2. Build lock to lock the barrel.
3. Lock the barrel. This will cause the game to crash.

### Mod version

V2.0.4

### Operating System

Mac IOS Monterrey v12.6.4

### Minecraft version

1.20.1

### Other mods

Advancement Plaques
Automobility
Better Archeology
Better Combat
Better End
Chunk Loaders
Clumps
Companion
Creeper Overhaul
Dungeons and Taverns
Extended Drawers
Geode+
Gravestones
Hellions Sniffer+
Horse Buff
Hostile Mobs Improve Over Time
Liberty's Villagers
Marium's Soulslike Weaponry
Mob Captains
More Mob Variants
Mutant Monsters
Simply Swords
Waystones

### Server

Doesn't happen

### Client

Happens

### Logs

I do not know what to put here, sorry

### Crash Report

---- Minecraft Crash Report ---- // Who set us up the TNT?  Time: 2023-07-27 16:13:28 Description: Rendering Block Entity  java.lang.NullPointerException: Rendering Block Entity 	at java.base/java.util.Objects.requireNonNull(Objects.java:208) 	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderIcon(AbstractDrawerBlockEntityRenderer.java:124) 	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderIcons(AbstractDrawerBlockEntityRenderer.java:114) 	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderSlot(AbstractDrawerBlockEntityRenderer.java:75) 	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.renderSlot(DrawerBlockEntityRenderer.java:87) 	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.render(DrawerBlockEntityRenderer.java:61) 	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.method_3569(DrawerBlockEntityRenderer.java:20) 	at net.minecraft.class_824.method_23079(class_824.java:90) 	at net.minecraft.class_824.method_23081(class_824.java:79) 	at net.minecraft.class_824.method_3554(class_824.java:104) 	at net.minecraft.class_824.method_3555(class_824.java:79) 	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275) 	at net.minecraft.class_761.handler$dfm000$sodium$onRenderTileEntities(class_761.java:12608) 	at net.minecraft.class_761.method_22710(class_761.java:1372) 	at net.minecraft.class_757.method_3188(class_757.java:1110) 	at net.minecraft.class_757.method_3192(class_757.java:880) 	at net.minecraft.class_310.method_1523(class_310.java:1219) 	at net.minecraft.class_310.method_1514(class_310.java:802) 	at net.minecraft.client.main.Main.main(Main.java:250) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at java.base/java.util.Objects.requireNonNull(Objects.java:208) 	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderIcon(AbstractDrawerBlockEntityRenderer.java:124) 	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderIcons(AbstractDrawerBlockEntityRenderer.java:114) 	at io.github.mattidragon.extendeddrawers.client.renderer.AbstractDrawerBlockEntityRenderer.renderSlot(AbstractDrawerBlockEntityRenderer.java:75) 	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.renderSlot(DrawerBlockEntityRenderer.java:87) 	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.render(DrawerBlockEntityRenderer.java:61) 	at io.github.mattidragon.extendeddrawers.client.renderer.DrawerBlockEntityRenderer.method_3569(DrawerBlockEntityRenderer.java:20) 	at net.minecraft.class_824.method_23079(class_824.java:90) 	at net.minecraft.class_824.method_23081(class_824.java:79) 	at net.minecraft.class_824.method_3554(class_824.java:104) 	at net.minecraft.class_824.method_3555(class_824.java:79) 	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275) 	at net.minecraft.class_761.handler$dfm000$sodium$onRenderTileEntities(class_761.java:12608) 	at net.minecraft.class_761.method_22710(class_761.java:1372) 	at net.minecraft.class_757.method_3188(class_757.java:1110)  -- Block Entity Details -- Details: 	Name: extended_drawers:drawer // io.github.mattidragon.extendeddrawers.block.entity.DrawerBlockEntity 	Block: Block{extended_drawers:quad_drawer}[facing=east] 	Block location: World: (906,138,1257), Section: (at 10,10,9 in 56,8,78; chunk contains blocks 896,-64,1248 to 911,319,1263), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,-64,1024 to 1023,319,1535) 	Block: Block{extended_drawers:quad_drawer}[facing=east] 	Block location: World: (906,138,1257), Section: (at 10,10,9 in 56,8,78; chunk contains blocks 896,-64,1248 to 911,319,1263), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,-64,1024 to 1023,319,1535) Stacktrace: 	at net.minecraft.class_824.method_3554(class_824.java:104) 	at net.minecraft.class_824.method_3555(class_824.java:79) 	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.renderTileEntities(SodiumWorldRenderer.java:275) 	at net.minecraft.class_761.handler$dfm000$sodium$onRenderTileEntities(class_761.java:12608) 	at net.minecraft.class_761.method_22710(class_761.java:1372) 	at net.minecraft.class_757.method_3188(class_757.java:1110) 	at net.minecraft.class_757.method_3192(class_757.java:880) 	at net.minecraft.class_310.method_1523(class_310.java:1219) 	at net.minecraft.class_310.method_1514(class_310.java:802) 	at net.minecraft.client.main.Main.main(Main.java:250) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- Affected level -- Details: 	All players: 1 total; [class_746['Sandel97'/589, l='ClientLevel', x=908.96, y=137.00, z=1255.70]] 	Chunk stats: 370, 370 	Level dimension: minecraft:overworld 	Level spawn location: World: (64,74,0), Section: (at 0,10,0 in 4,4,0; chunk contains blocks 64,-64,0 to 79,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 11914618 game time, 91223 day time 	Server brand: fabric 	Server type: Non-integrated multiplayer server Stacktrace: 	at net.minecraft.class_638.method_8538(class_638.java:458) 	at net.minecraft.class_310.method_1587(class_310.java:2406) 	at net.minecraft.class_310.method_1514(class_310.java:821) 	at net.minecraft.client.main.Main.main(Main.java:250) 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)  -- Last reload -- Details: 	Reload number: 1 	Reload reason: initial 	Finished: Yes 	Packs: vanilla, fabric  -- System Details -- Details: 	Minecraft Version: 1.20.1 	Minecraft Version ID: 1.20.1 	Operating System: Mac OS X (x86_64) version 12.6.4 	Java Version: 17.0.3, Microsoft 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft 	Memory: 666537528 bytes (635 MiB) / 1476395008 bytes (1408 MiB) up to 4294967296 bytes (4096 MiB) 	CPUs: 8 	Processor Vendor: GenuineIntel 	Processor Name: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz 	Identifier: Intel64 Family 6 Model 94 Stepping 3 	Microarchitecture: Skylake (Client) 	Frequency (GHz): 2.70 	Number of physical packages: 1 	Number of physical CPUs: 4 	Number of logical CPUs: 8 	Graphics card #0 name: Intel HD Graphics 530 	Graphics card #0 vendor: Intel 	Graphics card #0 VRAM (MB): 1536.00 	Graphics card #0 deviceId: 0x191b 	Graphics card #0 versionInfo: Revision ID: 0x0006, gMux Version: 4.0.29 [3.2.8] 	Graphics card #1 name: AMD Radeon Pro 455 	Graphics card #1 vendor: AMD (0x1002) 	Graphics card #1 VRAM (MB): 2048.00 	Graphics card #1 deviceId: 0x67ef 	Graphics card #1 versionInfo: Revision ID: 0x00c7, ROM Revision: 113-C980AF-908, VBIOS Version: 113-C9801AP-028, EFI Driver Version: 01.A0.908, gMux Version: 4.0.29 [3.2.8] 	Memory slot #0 capacity (MB): 8192.00 	Memory slot #0 clockSpeed (GHz): 2.13 	Memory slot #0 type: LPDDR3 	Memory slot #1 capacity (MB): 8192.00 	Memory slot #1 clockSpeed (GHz): 2.13 	Memory slot #1 type: LPDDR3 	Virtual memory max (MB): 18432.00 	Virtual memory used (MB): 10168.45 	Swap memory total (MB): 2048.00 	Swap memory used (MB): 514.50 	JVM Flags: 8 total; -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	Fabric Mods:  		advancementplaques: Advancement Plaques 1.4.9 		architectury: Architectury 9.1.10 		automobility: Automobility 0.4.2+1.20.1-fabric 			jsonem: JsonEM 0.2.1+1.20 		balm-fabric: Balm 7.0.4 		bclib: BCLib 3.0.11 			wunderlib: WunderLib 1.1.5 		betterarcheology: Better Archeology 1.0.2 		bettercombat: Better Combat 1.7.2+1.20.1 		betterend: Better End 4.0.8 		chunkloaders: Chunk Loaders 1.2.5 		cloth-config: Cloth Config v11 11.1.106 			cloth-basic-math: cloth-basic-math 0.6.1 		clumps: Clumps 12.0.0.1 		companion: Companion 5.0.2 		continents: Continents 1.1.2 		creeperoverhaul: Creeper Overhaul 3.0.1 			resourcefullib: Resourceful Lib 2.0.6 				com_teamresourceful_yabn: yabn 1.0.3 		dungeons_andtaverns_mr: Dungeons and Taverns 1-v2.1.3 		extended_drawers: Extended Drawers 2.0.3+mc.1.20.1 			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9 			config_toolkit: ConfigToolkit 1.0.0 				io_determann_shadow-api-17: shadow-api-17 0.1.1 				net_fabricmc_javapoet: javapoet 0.1.0 			graphlib: Graph Lib 1.1.1+1.20 				kmodlib-overlay: KModLib Overlay 0.2.4+1.20 				libnetworkstack: Lib Network Stack 0.10.0 			yet_another_config_lib_v3: YetAnotherConfigLib 3.0.3+1.20 				com_twelvemonkeys_common_common-image: common-image 3.9.4 				com_twelvemonkeys_common_common-io: common-io 3.9.4 				com_twelvemonkeys_common_common-lang: common-lang 3.9.4 				com_twelvemonkeys_imageio_imageio-core: imageio-core 3.9.4 				com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.9.4 				com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.9.4 		fabric-api: Fabric API 0.85.0+1.20.1 			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77 			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.0+97bb207577 			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77 			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77 			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377 			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377 			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.8+b3afc78b77 			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.12+b3afc78b77 			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77 			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77 			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.8+40e50c4677 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77 			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.38+b3afc78b77 			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.42+9e7660c677 			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77 			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.48+b3afc78b77 			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77 			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77 			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.0+6beca84877 			fabric-particles-v1: Fabric Particles (v1) 1.1.0+201a23a077 			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377 			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.8+e3d6ed2577 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77 			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.3+43a3fedd77 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77 		fabricloader: Fabric Loader 0.14.21 		farsight: Farsight Mod 1.20.1-3.7 			org_jctools_jctools-core: jctools-core 4.0.1 		forgeconfigapiport: Forge Config API Port 8.0.0 		geckolib: Geckolib 4.2.1 			com_eliotlash_mclib_mclib: mclib 20 		geode_plus: Geode+ 1.2.0 			paragon: Paragon 3.0.2 				blue_endless_jankson: jankson 1.2.1 				com_moandjiezana_toml_toml4j: toml4j 0.7.2 				org_yaml_snakeyaml: snakeyaml 1.27 		gravestones: Gravestones v1.15 		horsebuff: HorseBuff 2.1.1 		iceberg: Iceberg 1.1.11 		iris: Iris 1.6.4 			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1 		java: OpenJDK 64-Bit Server VM 17 		libertyvillagers: Liberty's Villagers 1.0.14+fabric+1.20.1 			server_translations_api: Server Translations API 2.0.0+1.20 				packet_tweaker: Packet Tweaker 0.4.0+1.19.4 		lithium: Lithium 0.11.2 		midnightlib: MidnightLib 1.4.1 		minecraft: Minecraft 1.20.1 		mob_captains_mr: Mob Captains 1-v2.1.2 		modmenu: Mod Menu 7.1.0 		moonlight: Moonlight 1.20-2.6.1 		moremobvariants: More Mob Variants 1.2.2 		mr_hostile_mobsimproveovertime: Hostile Mobs Improve Over Time 1.4.2 		mutantmonsters: Mutant Monsters 8.0.2 			cardinal-components-base: Cardinal Components API (base) 5.2.1 			cardinal-components-entity: Cardinal Components API (entities) 5.2.1 		patchouli: Patchouli 1.20.1-81-FABRIC 			fiber: fiber 0.23.0-2 		player-animator: Player Animator 1.0.2+1.19.4 		puzzleslib: Puzzles Lib 8.0.7 		resourcefulconfig: Resourcefulconfig 2.0.0 		simplyswords: Simply Swords 1.48.1-1.21 		snifferplus: Hellion's Sniffer+ 0.2.0 		sodium: Sodium 0.4.10+build.27 		soulsweapons: Marium's Soulslike Weaponry 0.9.9.6-1.20-fabric 		sound_physics_remastered: Sound Physics Remastered 1.20.1-1.1.1 		spawn_animations_mr: Spawn Animations 1.9.1 		starlight: Starlight 1.1.2+fabric.dbc156f 		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.7 		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.10+c 		tectonic: Tectonic 2.0.1 		tlc: The Lost Castle 1.0.1 		varietyapi: VarietyAPI 1.0 		voicechat: Simple Voice Chat 1.20.1-2.4.14 		waystones: Waystones 14.0.1 		weeping_angels: Weeping Angels 46.0.1 		xaerominimap: Xaero's Minimap 23.5.0 		you_died: You Died 3.0.0.17 	Loaded Shaderpack: (off) 	NEC status: No NEC detected 	Launched Version: fabric-loader-0.14.21-1.20.1 	Backend library: LWJGL version 3.3.1 SNAPSHOT 	Backend API: AMD Radeon Pro 455 OpenGL Engine GL version 4.1 ATI-4.8.101, ATI Technologies Inc. 	Window size: 3360x2100 	GL Caps: Using framebuffer using OpenGL 3.2 	GL debug messages: <disabled> 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'fabric' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: vanilla, fabric 	Current Language: en_us 	CPU: 8x Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz

**Comment by MattiDragon** [comment]
Install indium
