### ISSUE TITLE
[Feature]: Creative Vending upgrade

### ISSUE THREAD

**Issue by Stat1c-V01D** [MattiDragon/ExtendedDrawers#76]
### Description of the feature

As far as I could figure it out the creative storage upgrade just gives you almost infinite storage but not infinite of the item in the slot its applied to. It would be nice to have an upgrade that allows you to have an infinite amount of the item you place in the slot where the upgrade is applied to.
Either you could implement that functionality into the existing creative upgrade or add a separate item.

### How does it make the mod better?

QoL improvement for players that do not want to spend forever grinding for building blocks or similar or want to focus more on automation instead of ore hunting.

**Comment by MattiDragon** [comment]
Use the dupe wand to enable duping mode
