### ISSUE TITLE
[Feature]: drawers drop in creative if not empty

### ISSUE THREAD

**Issue by 800020h** [MattiDragon/ExtendedDrawers#79]
### Description of the feature

if you break the drawer in creative it should drop its self (only if it's not empty/upgraded)

### How does it make the mod better?

- parity with vanilla shulker boxes
- easier moving filled drawers in creative
- preventing item loss/hassle in some admin/testing situations

**Comment by MattiDragon** [comment]
This will be fixed in 2.0.8, which will soon be available for download
