### ISSUE TITLE
[Feature]: Create contraptions compat

### ISSUE THREAD

**Issue by SzczurekYT** [MattiDragon/ExtendedDrawers#85]
### Description of the feature

Currently when a drawer is attached to a moving contraptions it does nothing. Create is unable to neither insert or extract items from it.
It think it would be nice is create was able to work with drawers like with chests.

### How does it make the mod better?

This gives the mod better integration with create and would be helpful in situations where you would need to store big amount of one kind of items for example cobblestone for a moving drill. It could be also used to filter out what's stored and prevent unwanted items from being collected.

**Comment by MattiDragon** [comment]
I've checked creates code and they explicitly disable support for any modded container that isn't a chest or a barrel. You should consider opening and issue on their repo requesting support for drawers or an option to manually override. If create enables support for modded containers and drawers still don't work, feel free to reopen this issues.

Relevant lines of code if you want to include in the request: [MountedStorage line 75-79](https://github.com/Fabricators-of-Create/Create/blob/c1ba62240fb817820ade654b30d7157949c94fea/src/main/java/com/simibubi/create/content/contraptions/MountedStorage.java#L75-L79 )
