### ISSUE TITLE
[Crash]:  Upgrading Drawing with items in it. 

### ISSUE THREAD

**Issue by makumaku1974** [MattiDragon/ExtendedDrawers#87]
### Description of the issue

Cobblestone stack of 8 then upgrading the drawer with level 1 upgrade crashed the game and the world is unable to be used.

### Reproduction steps

1.  Any items inside the drawer
2. Upgrade it with level 1
3. boom crashes

### Mod version

2.1.0

### Operating System

Windows 11

### Minecraft version

1.20.4

### Other mods

Fabric Api 

### Server

Not tested

### Client

Happens

### Logs

https://gist.github.com/makumaku1974/c4f91a9f7d1c7bb52965ac2aeec6b54a

### Crash Report

https://gist.github.com/makumaku1974/c3b598237ae70643b5cc89c7b8b708d0

**Comment by MattiDragon** [comment]
Extended drawers depends on the fabric rendering api. If you use sodium you need to install indium to make this work. You might have to switch sodium versions to find a compatible indium

**Comment by makumaku1974** [comment]
> Extended drawers depends on the fabric rendering api. If you use sodium you need to install indium to make this work. You might have to switch sodium versions to find a compatible indium

Thanks, I'll test it now.
