### ISSUE TITLE
[Crash]: Drawer crash game of my friend when placed

### ISSUE THREAD

**Issue by WyxZer42** [MattiDragon/ExtendedDrawers#89]
### Description of the issue

Hello, on a server with my friend, placing a quad drawer with a iron upgrade in the up left corner, the game crashes

### Reproduction steps

1. Start on Fabric 1.20.2
2. Place a 4 drawer
3. Put a Level 2 upgrade in le up left corner 
4. Game crashes (not mine but my friend's one does)

### Mod version

v2.1.0

### Operating System

Windows 11/10

### Minecraft version

1.20.2

### Other mods

![image_2024-01-05_231707868](https://github.com/MattiDragon/ExtendedDrawers/assets/145154341/f4cb22c3-b880-400e-8722-98d7d39e86b7)

### Server

Doesn't happen

### Client

Happens

### Logs

https://pastebin.com/1qW2s2gJ

### Crash Report

The game crashed whilst rendering block entity Eror : java.lang.NullPointerException: Rendering Block Entity

**Comment by MattiDragon** [comment]
This is usually caused by using sodium without indium. Make sure they have it installed.
