### ISSUE TITLE
[Bug]: Using Controller with AE2 storage bus, when new drawer is added to network, need to break/replace storage bus

### ISSUE THREAD

**Issue by seanbyrne88** [MattiDragon/ExtendedDrawers#9]
### Description of the issue

Apologies if this is an AE2 issue.

When adding a new drawer to a network using the drawer controller block, if using the AE2 storage bus, the new drawer and it's contents do not show up in the AE2 network until a break and replace the storage bus.

### Reproduction steps

1. Add drawers and controller block
2. Attach AE2 Storage Bus
3. Contents should show in AE2 system
4. Add new drawer to drawer network and add contents
5. Drawer contents do not show in AE2 network until the storage bus is replaced.

### Mod version

1.2.1

### Operating System

Windows 10

### Minecraft version

1.18.2

### Other mods

Applied Energistics 2 11.1.4

### Server

Not tested

### Client

Not tested

### Logs

n/a

**Comment by MattiDragon** [comment]
I suspect this is because AE caches the available items. I'll see if I can make it update.

**Comment by MattiDragon** [comment]
According to an AE dev the cache is refreshed every few seconds. Have you tried waiting a bit?

**Comment by seanbyrne88** [comment]
Thanks for checking. Is this something that should be fixed in ExtendedDrawers or an AE2 issue?

**Comment by MattiDragon** [comment]
It's probably AEs fault, but I might be able to fix it on my end too

**Comment by MattiDragon** [comment]
Seems like AE fixed it. Reopen if this still occurs
