### ISSUE TITLE
[Bug]: Compacting Drawers Display

### ISSUE THREAD

**Issue by A5ho9999** [MattiDragon/ExtendedDrawers#90]
### Description of the issue

Well they don't seem to display correctly and/or work correctly?
![2024-01-09_13 00 47](https://github.com/MattiDragon/ExtendedDrawers/assets/46066364/a24b3c82-3f58-4ccd-8dac-ed4d4fe64c3f)

When attempting to click on the iron ingots in the top left, I get Block of Iron and sometimes a ghost Iron Ingot. If I click on the slots that don't have displays I can still place and remove items in those slots but they don't appear.

### Reproduction steps

1. Load and see I guess?

### Mod version

https://modrinth.com/mod/extended-drawers/version/2.1.0+mc.1.20.1

### Operating System

Windows 10

### Minecraft version

1.20.1 (Fabric Loader 0.15.3)

### Other mods

Fabric)GlowInkPlus-1.20-1.2.0.jar
Adorn-5.0.1+1.20.1-fabric.jar
AirHop-v8.0.0-1.20.1-Fabric.jar
AmbientEnvironment-fabric-1.20.1-11.0.0.1.jar
BeaconOverhaul-1.8.4+1.20.jar
BetterAnimationsCollection-v8.0.0-1.20.1-Fabric.jar
BetterF3-7.0.2-Fabric-1.20.1.jar
BetterPingDisplay-Fabric-1.20.1-1.1.1.jar
Bookshelf-Fabric-1.20.1-20.1.8.jar
BotanyPots-Fabric-1.20.1-13.0.18.jar
BotanyTrees-Fabric-1.20.1-9.0.7.jar
Bovines-And-Buttercups-Fabric-1.9.0+1.20.1.jar
Chunky-1.3.92.jar
Clumps-fabric-1.20.1-12.0.0.3.jar
Compress-It-2.5.0-1.20.x-fabric.jar
Compressed Blocks-fabric-1.20.2-1.4.2.jar
Controlling-fabric-1.20.1-12.0.2.jar
CottageCraft-1.4.1-1.20+.jar
CottageCraftAxolotls-1.2.0-1.20.1+.jar
CraterLib-Fabric-1.20-1.1.1.jar
Croptopia-1.20-FABRIC-2.3.0.jar
DarkPaintings-Fabric-1.20.1-17.0.4.jar
DeathKnell-Fabric-1.20.1-10.0.4.jar
DetailArmorBar-2.6.3+1.20.1-fabric.jar
DiagonalFences-v8.1.3-1.20.1-Fabric.jar
DramaticDoors-QuiFabrge-1.20.1-3.1.5.jar
ExtendedDrawers-2.1.0+mc.1.20.1.jar
ExtensibleEnums-v7.0.1.242-1.20-Fabric.jar
FancySporeBlossom-fabric-1.20.1-1.1.0.jar
Floral Enchantment-Fabric-1.20.1-1.1.4.jar
ForgeConfigAPIPort-v8.0.0-1.20.1-Fabric.jar
Gamma-Utils-1.7.16-mc1.20.1.jar
GlassCarpet-1.1.0-1.20.jar
Iceberg-1.20.1-fabric-1.1.18.jar
InvView-1.4.12-1.20+.jar
Item_Obliterator-Fabric_Quilt-MC1.20.1-1.7.0.jar
Jade-1.20-fabric-11.7.0.jar
JustMoreCakes-fabric-1.20.1-1.13.1.jar
ManyFlowers-1.20.1-1.4.jar
MergedStats-1.2.0.jar
MobLassos-v8.0.0-1.20.1-Fabric.jar
ModernKeyBinding-Fabric-1.20-1.2.0.jar
MoreCullingExtra-1.1-1.20.1.jar
NE-1.20.1-1.9.0.jar
Necronomicon-Fabric-1.3.0.jar
NoFog-1.3.5+1.16.5-1.20.4.jar
PacketFixer-fabric-1.2.1-1.20.1.jar
Patchouli-1.20.1-84-FABRIC.jar
Pehkui-3.7.12+1.14.4-1.20.4.jar
PuzzlesLib-v8.1.12-1.20.1-Fabric.jar
Resourcify (1.20-1.20.1-fabric)-1.2.1.jar
RoughlyEnoughItems-12.0.665.jar
RoughlyEnoughProfessions-fabric-1.20.1-2.0.2.jar
SCME-7.2.jar
Searchables-fabric-1.20.1-1.0.2.jar
Shut Up GL Error-fabric-1.20.1-1.0.0.jar
SimpleDiscordLink-Combo-1.20-3.0.1.jar
SimpleRPC-fabric-1.20-3.2.4.jar
Soulbound-Fabric-0.6+1.20.1.jar
SpongeSucc (Lava Sponge)-2.0.0-1.20+.jar
TerraBlender-fabric-1.20.1-3.0.1.2.jar
TotemPartyPopper-3.0.0-1.20+.jar
VillagersPlus_3.1_(FABRIC)_for_1.20.1.jar
Vinery - 1.4.5 - FABRIC - 1.20.1.jar
XaerosWorldMap_1.37.2_Fabric_1.20.jar
Xaeros_Minimap_23.9.3_Fabric_1.20.jar
YSNS-Fabric_Quilt-1.0.5.jar
Yeeterite-2.0.0beta8-1.20+.jar
YungsApi-1.20-Fabric-4.0-beta0.jar
YungsBetterDesertTemples-1.20-Fabric-3.0.jar
YungsBetterDungeons-1.20-Fabric-4.0.jar
YungsBetterMineshafts-1.20-Fabric-4.0.jar
YungsBetterNetherFortresses-1.20-Fabric-2.0.jar
YungsBetterOceanMonuments-1.20-Fabric-3.0.jar
YungsBetterStrongholds-1.20-Fabric-4.0.3.jar
YungsBetterWitchHuts-1.20-Fabric-3.0.jar
Zoomify-2.11.2.jar
abstoneedition-2.1.3-fabric-mc1.20.jar
abverticaledition-1.0.3b-fabric-mc1.20.jar
accurate-block-placement-1.2.1.jar
additionallanterns-1.1.1-fabric-mc1.20.jar
alternate-current-mc1.20-1.7.0.jar
amecs-1.3.10+mc.1.20.1.jar
amethyst-cutting-1.0.jar
anvilrestoration-1.20.1-2.2.jar
appliedenergistics2-fabric-15.0.19.jar
architectury-9.1.12-fabric.jar
areas-1.20.1-5.3.jar
armor-stand-editor-2.1.2+1.20.1.jar
armorchroma-1.2.6.jar
armourersworkshop-fabric-1.20.1-2.0.11.jar
async-locator-fabric-1.20-1.3.0.jar
athena-fabric-1.20.1-3.1.1.jar
badpackets-fabric-0.4.3.jar
balm-fabric-1.20.1-7.2.1.jar
banner-flags-2.1.jar
bclib-3.0.14.jar
beautify-1.1.0+fabric-1.20.jar
beproud-0.1.1.jar
better-enchanted-books-1.20-1.4.3.jar
better-end-4.0.11.jar
betterchunkloading-fabric-1.20.1-2.3.jar
betterleads-1.1.0+1.20.1.jar
betterlily-1.20-1.3.2-fabric.jar
betterstats-3.7.1+fabric-1.20.1.jar
bigger_end_cities-1.20.1-1.0.4.jar
biolith-1.0.0-beta.1.jar
biomemakeover-FABRIC-1.20.1-1.11.4.jar
blockus-2.7.10+1.20.1.jar
brrp-fabric-1.0.1-1.20.1.jar
bushierflowers-0.0.3-1.20.1.jar
cardinal-components-api-5.2.2.jar
carpet-extra-1.20-1.4.115.jar
carpet-fixes-1.20-1.16.1.jar
carpet-layers-1.1.0.jar
carpet-tis-addition-mc1.20.1-v1.55.0.jar
carrier-1.12.0.jar
cat_jam-fabric-mc1.20-1.2.1.jar
charmofundying-fabric-6.4.5+1.20.1.jar
cherry-villages-1.0.3.jar
chipped-fabric-1.20.1-3.0.1.jar
chunksending-fabric-1.20.1-2.6.jar
cinderscapes-4.0.10.jar
clean_tooltips-1.0-fabric-1.20.1.jar
clientcrafting-fabric-1.20.1-1.6.jar
clientcrafting-fabric-1.20.1-1.7.jar
cloth-config-11.1.118-fabric.jar
clutter-1.20-0.5.7.jar
collective-1.20.1-7.30.jar
comforts-fabric-6.3.4+1.20.1.jar
compressed-blocks-1.12.jar
connectedglass-1.1.11-fabric-mc1.20.1.jar
connectivity-fabric-1.20.1-4.5.jar
continuity-3.0.0-beta.4+1.20.1.jar
cookingforblockheads-fabric-1.20-16.0.1.jar
craftingtweaks-fabric-1.20-18.2.2.jar
create-sodium-fix-0.5.1-d-build.5+mc1.20.1.jar
ctov-3.3.6.jar
ctov-beautify-compat-2.0.jar
ctov-croptopia-compat-2.0.jar
ctov-friends-and-foes-compat-2.0.jar
ctov-villagers-plus-compat-2.0.jar
cupboard-fabric-1.20.1-2.1.jar
custompaintings-2.1.0+1.20.jar
dark-loading-screen-1.6.14.jar
dawn-5.0.0.jar
disguiseheads-fabric-1.0.1-mc1.20.jar
doapi-1.2.8-fabric.jar
dragondropselytra-1.20.1-3.2.jar
ears-fabric-1.20-1.4.6.jar
earth2java-fabric-1.10.1+1.20.1.jar
enchanted-vertical-slabs-1.9.1.jar
enchantedshulkers-mc1.20.1-v1.2.3.jar
enhancedblockentities-0.9+1.20.jar
entityculling-fabric-1.6.2-mc1.20.1.jar
experiencebottler-1.20.1+build.2.jar
extremesoundmuffler-3.41-fabric-1.20.jar
extshape-fabric-2.0.9-mc1.20.1.jar
extshape_blockus-fabric-2.0.7-mc1.20.1.jar
fabric-api-0.91.0+1.20.1.jar
fabric-carpet-1.20-1.4.112+v230608.jar
fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar
fallingleaves-1.15.4+1.20.1.jar
farmingforblockheads-fabric-1.20.1-14.0.2.jar
fastrandom-2.0.0.jar
ferritecore-6.0.1-fabric.jar
forgottengraves-1.20.1-3.2.5.jar
freecam-fabric-1.1.10+1.20.jar
friendsandfoes-beekeeperhut-fabric-mc1.20-1.3.0.jar
friendsandfoes-fabric-mc1.20.1-2.0.7.jar
friendsandfoes-flowerymooblooms-fabric-mc1.20.1-2.0.0.jar
fusion-1.1.0c-fabric-mc1.20.1.jar
gardeners-dream-1.jar
geckolib-fabric-1.20.1-4.3.1.jar
geophilic-v2.1.0-mc1.20u1.20.2.jar
giant-crops-1.20-1.0.1.jar
glassbreaker-fabric-1.4.0+1.20.jar
gottagofast-1.1.0-dev.jar
gpumemleakfix-fabric-1.20.1-1.7.jar
handcrafted-fabric-1.20.1-3.0.5.jar
harvestwithease-1.20.1-8.0.0.2-fabric.jar
head-name-fix-1.20-1.2.2.jar
icarus-1.16.jar
immersive_paintings-0.6.7+1.20.1-fabric.jar
improvedsigns-1.3.1.jar
indium-1.0.27+mc1.20.1.jar
infinitetrading-1.20.1-4.3.jar
iris-mc1.20.1-1.6.11.jar
isometric-renders-0.4.5+1.20.jar
jamlib-0.6.1+1.20.x.jar
jeed-1.20-2.1.7-fabric.jar
justplayerheads-1.20.1-3.3.jar
language-reload-1.5.10+1.20.1.jar
leaky-fabric-1.20.1-1.6.jar
ledger-1.2.8.jar
letsdo-bakery-fabric-1.1.3b.jar
letsdo-beachparty-fabric-1.1.2.jar
letsdo-candlelight-fabric-1.2.7.jar
letsdo-meadow-fabric-1.3.3.jar
lighty-fabric-2.1.2+1.20.1.jar
lithium-fabric-mc1.20.1-0.11.2.jar
logprot-fabric-1.20.1-3.1.jar
mavapi-1.1.3-mc1.20.1.jar
mavm-1.2.4-mc1.20.jar
mc-server-description-4.1.0+1.20.1.jar
memoryleakfix-fabric-1.17+-1.1.5.jar
memoryusagescreen-fabric-mc1.20-1.9.0.jar
mes-1.3-1.20-fabric.jar
midnightlib-fabric-1.4.1.1.jar
mmode-fabric-1.20-1.1.1.jar
modmenu-7.2.2.jar
moonlight-1.20-2.8.81-fabric.jar
more-axolotl-2.0.1-1.20.jar
moreculling-1.20.4-0.21.0.jar
morefrogs-1.20.1-1.2.5-fabric.jar
moreladders-1.3-1.20.jar
moremcmeta-1.20.1-4.4.6-fabric.jar
moremobvariants-fabric+1.20-1.2.2.jar
morestats-1.3.0+1.20.jar
morezombievillagers-1.20.1-3.5.jar
mousewheelie-1.13.0+mc1.20.1.jar
neruina-1.3.0-fabric+1.18.2-1.20.1.jar
nicer-skies-1.2.0.jar
nicerportals-1.2.1+1.20.jar
no-more-purple-1.2.1+1.20.1.jar
notenoughanimations-fabric-1.7.0-mc1.20.1.jar
nvidium-0.2.5-beta.jar
our-villager-discounts-1.20.1+build.0-fabric.jar
owo-lib-0.11.2+1.20.jar
particle-rain-2.0.8.jar
passiveendermen-1.20.1-4.6.jar
placeholder-api-2.1.3+1.20.1.jar
plantinajar-2.5.3.jar
player-pronouns-2.0.0+1.20.1.jar
plushies-1.4.0-fabric.jar
polymorph-fabric-0.49.1+1.20.1.jar
portabletables-fabric-1.20.1-2.4.jar
pride-furnaces-1.0.1+1.20.jar
promenade-4.1.1.jar
purpurpack-breed-axolotl-with-tropical-fish-item-1.2.jar
purpurpacks-more-dyed-wool-and-carpet-2.3.jar
purpurpacks-pickaxe-effective-light-source-blocks-1.3.jar
purpurpacks-re-dye-concrete-powder-1.3.jar
purpurpacks-re-dye-glass-1.3.jar
purpurpacks-re-dye-terracotta-1.3.jar
quickshulker-1.4.0-1.20.jar
rainglow-1.1.2+mc1.20.1.jar
randomblockplacement-1.20-fabric0.83.0-1.1.4.jar
reacharound+1.20-1.1.2.jar
reeses_sodium_options-1.6.5+mc1.20.1-build.95.jar
refined-advancements-1.0.3a.jar
reinforced-barrels-2.4.1+1.20.jar
reinforced-chests-2.4.2+1.20.jar
reinforced-shulker-boxes-2.5.0+1.20.jar
repurposed_structures-7.1.11+1.20.1-fabric.jar
resourcefullib-fabric-1.20.1-2.1.20.jar
rlovelyr-fabric-1.20.1-1.1.0.jar
rocks-1.7.1.jar
ruined-equipment-2.3.1+1.20.1.jar
servercore-fabric-1.3.9+1.20.1.jar
shulkerboxtooltip-fabric-4.0.4+1.20.1.jar
shulkerdropstwo-1.20.1-3.3.jar
simple-armor-hud-1.20.2-1.3.2.jar
simplehats-fabric-1.20.1-0.2.0.jar
simpleshulkerpreview-2.4.0.jar
simplevillagers-1.4.5.jar
sizeshiftingpotions-1.7.0-fabric.jar
skinlayers3d-fabric-1.6.1-mc1.20.1.jar
smoothchunk-fabric-1.20.1-3.2.jar
sneaky-mc1.20.1-1.0.10.jar
sodium-extra-0.5.1+mc1.20.1-build.112.jar
sodium-fabric-mc1.20.1-0.5.3.jar
spark-1.10.53-fabric.jar
stackableflowers-1.1.jar
stairdoors-1.0.0.jar
status-fabric-1.20.1-1.0.5.jar
styled-chat-2.2.3+1.20.1.jar
styled-nicknames-1.2.1+1.20.jar
styledplayerlist-3.1.1+1.20.1.jar
supermartijn642configlib-1.1.8a-fabric-mc1.20.jar
supermartijn642corelib-1.1.16-fabric-mc1.20.1.jar
supplementaries-1.20-2.7.21-fabric.jar
telekinesis-fabric-2.3.1-1.20.1.jar
terrestria-6.0.13.jar
things-0.3.3+1.20.jar
tooltiprareness-1.0.9.jar
tooltipsplus-1.2.6+1.20.jar
trashcans-1.0.18-fabric-mc1.20.jar
travelers-backpack-1.20.1-9.1.9.jar
traverse-7.0.11.jar
trinkets-3.7.1.jar
universal_shops-1.3.2+1.20.1.jar
usageticker-1.0.1-1.20.jar
veinmining-fabric-1.2.1+1.20.1.jar
villagerconfig-4.0.3+1.20.1.jar
voicechat-fabric-1.20.1-2.4.32.jar
vulpine-1.0.1.jar
wicked-paintings-1.4.0+1.20.1.jar
windchimes-1.2.4+1.20.jar
wormhole-1.1.15-fabric-mc1.20.jar
wraith-colormeoutlines-1.1.2.jar
yet-another-config-lib-fabric-3.2.1+1.20.jar
ComplementaryReimagined_r5.0.1.zip

### Server

Happens

### Client

Doesn't happen

### Logs

Not of use sadly (unless you really want to look through 1000s of warnings and errors from other mods)

### Extra Context

Breaking and replacing didn't seem to have affect either

**Comment by MattiDragon** [comment]
Could you please try reducing the mod set required for testing? That's way too many for me to test with

**Comment by A5ho9999** [comment]
Sure, I'll try and play around with it tomorrow (in 12 hour time)

**Comment by A5ho9999** [comment]
So I've reduced it being a possible conflict with Yeeterite-2.0.0beta8/9-1.20+.jar which weirdly enough is one of mine. So knowing what is there, I honestly don't see what could be conflicting. We recently updated from 2.0.8 to 2.1.0 yesterday but I also updated Yeeterite so unsure which. I'll try and play around with my newly added stuff and see if anything changes. It's very strange that it only happens on a dedicated server as well. Just letting you know in-case you find something that I don't

**Comment by A5ho9999** [comment]
I was able to find and fix it on my end, who would of thought using the TooltipCallbackEvent would break so many things despite being wrapped in very clear If statements. Sorry for bothering you

**Comment by MattiDragon** [comment]
@A5ho9999 I'm curious. How did you manage to break compacting drawers with the tooltip event? Did you accidentally mutate the stack or something?

**Comment by A5ho9999** [comment]
Well turns out it's very simple to do I guess. All I added back just now to test was, I guess I was breaking all the Nbt data when I should be been checking hasNbt first.
```
ItemTooltipCallback.EVENT.register(((stack, context, lines) -> {
            if (stack.getOrCreateNbt().contains("Tag")) {

            }
        }));
```
