### ISSUE TITLE
Not a Feature Request, just reaching out for some clarification on editing the Server config.

### ISSUE THREAD

**Issue by bkMiggs** [MattiDragon/ExtendedDrawers#91]
### Description of the feature

Which server files do I need to edit to change a drawers capacity?  I can make the change on a single player world by editing the extended_drawers.json but, probably unsurprisingly, doing this on the server doesn't work.  I've tried following your customization instructions on Curse where you say "There are two files: one for client side setting and one for settings needed on both the server and client.", but the only seemingly applicable file I can find on the server is the same extended_drawers.json.  

What am I doing wrong?

### How does it make the mod better?

Thanks for your help.

**Comment by MattiDragon** [comment]
The instructions are outdated. To edit the server config you just need to edit the `extended_drawers.json` file in the servers `config` folder. You should also make the same changes on the client for better compatibility. You might have to restart the server for the changes to load, I don't remember if I included a command to reload it or not.

**Comment by bkMiggs** [comment]
I got it working as soon as I rebooted the server.  Perfect.  Thanks for your help!
