### ISSUE TITLE
[Bug]: Upgrade duplication bug

### ISSUE THREAD

**Issue by radaelilucca** [MattiDragon/ExtendedDrawers#92]
### Description of the issue

Upgrades are duplicated when replaced.

### Reproduction steps

1. Place a drawer;
2. Access drawer GUI;
3. Add an upgrade;
4. Replace the upgrade with a new one (holding the new upgrade instead of removing the old one first);
5. The old upgrade will be grabbed but the drawer will drop a copy of it;

### Mod version

2.1.1+mc.1.20.1

### Operating System

Windows 11

### Minecraft version

1.20.1

### Other mods

- Fabric API 0.91.0+1.20.1
- Sodium mc1.20.1-0.5.3
- Indium 1.0.27+mc1.20.1

### Server

Not tested

### Client

Happens

### Logs

-

### Extra Context

https://github.com/MattiDragon/ExtendedDrawers/assets/29178479/9b21b1ef-43af-4e24-bca3-9f78b4e37467

**Comment by MattiDragon** [comment]
The drawer GUI is added by ExtendedDrawersAddon. They are responsible for issues caused by the ui. If you can reproduce the issue without the addon, then feel free to reopen the issue.
