### ISSUE TITLE
[Bug]: Missing Textures

### ISSUE THREAD

**Issue by ArgyTheFox** [MattiDragon/ExtendedDrawers#94]
### Description of the issue

The single, double, and quad drawers are not displaying textures.

![image_2024-01-29_231132182](https://github.com/MattiDragon/ExtendedDrawers/assets/110772597/44e87ccf-a1c0-46d8-9879-c07912a14888)

### Reproduction steps

Untested

### Mod version

1.4.5

### Operating System

Windows 10

### Minecraft version

1.19.2

### Other mods

Untested

### Server

Not tested

### Client

Happens

### Logs

[23:04:18] [Render thread/ERROR]:  Signature is missing from textures payload

**Comment by MattiDragon** [comment]
The logs aren't relevant. You need to install the latest version of thonkutil (it might be hidden as beta). Some mods bundle an old version of it that breaks the drawer model. I fixed it on their side, but the users haven't updated. If the issue persists, feel free to reopen the issue.
