### ISSUE TITLE
[Bug]: Storage Drawers no longer connected after update

### ISSUE THREAD

**Issue by ItsHipToCodeBees** [MattiDragon/ExtendedDrawers#95]
### Description of the issue

Despite them being physically connected, my storage drawers no longer recognize eachother after an update. I have to break and re place them in order for them to recognize the ones next to them. I tried simply updating the blocks by placing blocks next to drawers, but that does not work. This issue is a big problem for those of us with large amounts of drawers we cant possibly break and place individually again.

### Reproduction steps

1. Update from 1.19.2 to 1.20.1

### Mod version

v2.1.1

### Operating System

Windows 10

### Minecraft version

1.20.1

### Other mods

Fabric Loader 0.15.7
Fabric API 0.92.0

### Server

Not tested

### Client

Not tested

### Logs

https://gist.github.com/ItsHipToCodeBees/8022c1b9cf6c1ea7f9bffb77d4449f34

**Comment by MattiDragon** [comment]
I'm pretty sure graphlib (the library behind the drawer network logic) did a major change to the storage format there. You can use a subcommand of `/graphlib` to update areas without placing the drawers. Overall I wouldn't recommend updating minecraft version when using mods as many devs (myself included) use minecraft version changes as a place to introduce breaking changes to storage formats. It's likely that you might lose upgrades or other data if you update with mods. I'll close this as I don't plan on supporting migration between major minecraft versions. Feel free to ask questions about how to fix the network though.

**Comment by ItsHipToCodeBees** [comment]
Thank you so much for the quick reply! The suggested command has worked, and has fixed my storage system.
