### ISSUE TITLE
[Crash]: Ticking block entity | java.lang.NullPointerException: Cannot read field "parts" because "this.cachedStorage" is null

### ISSUE THREAD

**Issue by joex92** [MattiDragon/ExtendedDrawers#98]
### Description of the issue

So I play in a server with a small community and we have a Vanilla++ server, we added the drawers, create and few other extra block mods... 
in my base I have a bunch of drawers for many things and I use the Access Point to unload create contraptions, and I  used to use an Access Point to get items from the drawers with a smart chute... thing is that I was unloading a drill contraption and I went afk for a while while that was happening... then a restart happened and I have a reconnect mod, so my account reconnected seconds after restart... but when I came back I noticed the server was constantly crashing everytime I reconnected, and the crash log showed that the issue was on the smart chute that was interacting with the AP, so I told them to break the block with a command and it was resolved... that was like the 3rd time that that happened, before I had an AP with a smart chute getting all the seeds from different drawers (more than 4 types of seeds) to compost them, and I didn't disconnect I just went flying really far away and then came back flying and the server crashed just when I loaded the chunk where the AP was...

### Reproduction steps

1. place a lot of drawers with different items and using more than 1 chunk (recreating an industrial base where items are in different places)
2. connect all the drawers with the connector block so you can access all of them with 1 AP
3. with a smart chute start sending a lot of items to all the drawers
4. quickly leave the place or disconnect from the server long enough for the chunks to unload from memory (or just restart the server)
5. reconnect or come back and just when the chunk where the AP is located is loaded, the server should crash

### Mod version

2.1.0

### Operating System

Windows 10 (client), some Linux distribution (Server)

### Minecraft version

1.20.1

### Other mods

this is a zip with all the mods: https://drive.google.com/file/d/1a1kl8h9qlnmgWOdio_GZikL9q4fTK-2l/view
here's a screenshot of the list:
![image](https://github.com/MattiDragon/ExtendedDrawers/assets/645579/873ce623-aa18-416d-a510-a92d8eb6b492)
on top of these, I believe there's the Spark mod, dynmap, discord mod (I do not know the versions of these ones because I'm not an admin)

### Server

Happens

### Client

Not tested

### Logs

https://pastebin.com/c5kzNdQ0

### Crash Report

https://pastebin.com/c5kzNdQ0

### Extra Context

_the log and crash link are the same... I was not shared the minecraft logs... sorry... only the crash log..._

I guess what happened is that when the chunk was loaded, it tried to send the item to a drawer that should exists but it wasn't loaded, idk how the code works but I believe that maybe some kind of loop happened and the server crashed..? because it couldn't find the drawer although it wasn't loaded..? that's just my guess... if you believe this could be a Create side issue, I would just forward this to them...

**Comment by MattiDragon** [comment]
Update your extended drawers. The 2.1.1 updated fixed this bug
