### ISSUE TITLE
Fabric: Drawer Access Points stop working [Bug]: 

### ISSUE THREAD

**Issue by Knito58** [MattiDragon/ExtendedDrawers#99]
### Description of the issue

After they worked very well with tom's storage and advanced networking the access points stopped working. There were some (many) crashes from other sources (3d driver not working well) in between.
The Access Points (I have 3 of them: 1 for adv network, 1 for toms storage and 1 for coming home and emptying hands) do nothing. When double clicked there is no hand animation and the inventory items are not taken.
The **live log** not even flinches. Nothing there. Breaking and replacing the access points not helps.

Putting the items into the system by double clicking the respective drawers just works fine.
The drawer do work for themselves but any connection to the outside is lost.

The storage system has lost all items that were stored in the drawers and the advanced network is not able to put items into the system as before. The access points are dead even when directly accessed from the player.

Restarting the game from scratch not helps.
Reloading the world not helps.
Opening to LAN and allowing Cheats and typing "reload" reloads mods and datapacks. Cannot find the right trigger or function call.  This also not helps.

Single Player Survival MC version **1.20.4 with Fabric loader 0.96.11** no Optifine.

Is there a command which would revive the access points st like "trigger extended_drawers:load" ?

### Reproduction steps

No way. Install win 11 and have a not working 3d driver which boots your system while playing Minecraft. Leave a well working base and come home to a stuck one.

### Mod version

V2.11 for Fabric, Quilt 1.20.4

### Operating System

Win 11

### Minecraft version

1.20.4

### Other mods

Tom's Storage 1.20.4-1.6.11 Fabric
Advanced Networking V3.1.0 Fabric

### Server

Not tested

### Client

Happens

### Logs

No log enty generated

**Comment by MattiDragon** [comment]
You can use the `/graphlib extended_drawers:drawers updateblocks` command to update the drawer graph in a region. If you want you can also use the `/graphlib extended_drawers:drawers debugrender start` command to show the network. Breaking and placing the blocks should also fix the issue.
